### ISSUE TITLE
Redesign ZPoll and use new libzmq poller API

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#105]
zmq_poll has become extremely slow on Windows starting with some libzmq 4.x version (ca. 500 times slower than with libzmq 3.x). In libzmq 4.2.x, a new poller API is available, consisting of several zmq_poller_* functions. These should be used in clrzmq4, if available. However, this requires a redesign of the clrzmq ZPollItems class, which separates registration of poll items (which should only be done once), and waiting for new events on a given set of poll items.

**Comment by metadings** [comment]
I do recommend you [`./ZGuideExamples.exe AsyncSrv`](https://github.com/metadings/zguide/blob/master/examples/C%23/asyncsrv.cs), coming within [Pieter Hintjens' ZGuide Examples]([`github.com/booksbyus/zguide`](https://github.com/booksbyus/zguide/)).

You may do so in your favorite IDE when solution `clrzmq4` is opened,
by `git clone` [github.com/booksbyus/zguide](https://github.com/booksbyus/zguide/), then add the existing project `~/examples/C#/ZGuideExamples.mono.csproj`. Build the solution (F8 in MonoDevelop) :smile:

The AsyncSrv example uses ZPollItems in the Client, which is going to "REQuest" the Server.
