### ISSUE TITLE
ZFrame constructors should ensure the postcondition Position == 0

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#110]
Currently, the ZFrame constructors accepting a string will position the ZFrame stream at the end. This makes the use confusing. It might even be considered a bug.

**Comment by sigiesec** [comment]
E.g. the following code will not work as expected (see https://stackoverflow.com/questions/42768088/c-sharp-zframe-data-extraction):
```
ZMessage msg = new ZMessage();   
msg.Add(new ZFrame("AABBCCDD"));            
var str = msg.PopString();
```
str will be empty afterwards.

Alternatives to changing the behaviour of the ZFrame constructors, this might be fixed by

1. Rewinding a ZFrame on ZMessage.Add
1. Rewinding a ZFrame on ZMessage.Pop

However, I think changing the behaviour of the ZFrame constructors is preferrable.

**Comment by sigiesec** [comment]
See also #111, which would eliminate this issue along.

**Comment by metadings** [comment]
Closing this issue. It's too old
