### ISSUE TITLE
ZMQ Security

### ISSUE THREAD

**Issue by langroodi** [zeromq/clrzmq4#116]
None of PLAIN and CURVE ZMQ Security are wrapped on clrzmq4. Implementing _zauth_ and _zcert_ functions to clrzmq, make the binding more secure and useful than before. I hope you plan to add these features on the next milestone.

Thanks,

**Comment by sigiesec** [comment]
clrzmq4 is a binding to libzmq, not to czmq (which offers zauth and zcert). I think you imagine a completely different library.
