### ISSUE TITLE
Unable to Build with VisualStudio 2012 : Source file 'Monitoring\ZMonitorSocketExtensions.cs' not found

### ISSUE THREAD

**Issue by chuckmoore55** [zeromq/clrzmq4#12]
Hi,

Nice work on the project. I'm testing using it to talk 'ZeroMQ' with PowerShell.

Steps: 
1. Downloaded ZIP to C:\Temp, and extracted files. 
2. Clicked on 'ZeroMQ.VS.csproj' to start VS2012 (V11.Version 11.0.61030.00 Update 4)
3. Tried Build and got message about 'ZMonitorSocketExtensions'. 
4. Verified 'Monitoring\ZMonitorSocketExtensions.cs' does not exist

Am I not doing something correctly ?
Chuck

**Comment by metadings** [comment]
Well you are doing all right, but found me updating the `ZeroMQ.VS.csproj` and `ZeroMQ.mono.csproj`...

Please try again by downloading the ZIP or `git pull origin master`...!

I renamed `ZMonitorSocketExtensions.cs` to `ZMonitors.cs` and I was also adding a `static class Z85` (in the `Z85.cs`), which shall implement the `zmq_z85_encode` and `zmq_z85_decode` functions...

**Comment by chuckmoore55** [comment]
Metadings -- It built with no problems. Thanks for the quick response!

Chuck

**Comment by metadings** [comment]
One of the most astonishing [samples of code](https://github.com/zeromq/clrzmq4/blob/master/ZActor.cs#L48) are, that I have

``` csharp
    public string Endpoint { get; protected set; }

    public ZContext Context { get; protected set; }

    protected ZSocket Backend { get; set; }

    protected ZAction Action { get; set; }

    protected object[] Arguments { get; set; }

    public ZSocket Frontend { get; protected set; }


    public delegate void ZAction(ZContext context, ZSocket backend, CancellationTokenSource cancellor, object[] args);
```

With a new socket Backend, bound to an Endpoint (random), I am calling the delegate ZAction...!

``` csharp
    protected override void Run()
    {
        using (Backend = ZSocket.Create(Context, ZSocketType.PAIR))
        {
            Backend.Bind(Endpoint);

            Action(Context, Backend, Cancellor, Arguments);
        }
    }
```

Because the Start method also runs the Frontend, I can now listen on the messages:

```
    public override void Start()
    {
        base.Start();
        if (Frontend == null)
        {
            Frontend = ZSocket.Create(Context, ZSocketType.PAIR);
            Frontend.Connect(Endpoint);
        }
    }
```
