### ISSUE TITLE
v4.1.0.23 Travis-CI builds are broken

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#126]
The Travis-CI.org builds are broken since #119, maybe because of the changes in 729e8bd8f3d789b649ff575086a1f662f31aba60

@metadings Could you please fix that? I don't know why you did those changes.

**Comment by metadings** [comment]
Please look into ZeroMQ.VS.csproj, and re-add

    <None Include="i386\libzmq.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

     </None>
    <None Include="amd64\libzmq.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

This will enable Linux libzmq.so also to work within Visual Studio.

I've removed libsodium, in favor of tweetnacl (on Linux, you may do so on Windows too).

**Comment by sigiesec** [comment]
I don't think this is the problem, there seems to be an issue with the new .so file itself and its dependencies (https://travis-ci.org/zeromq/clrzmq4/jobs/272816515#L3358):

```
nunit-agent.exe Warning: 0 : UnmanagedLibrary[libsodium] Unable to extract the EmbeddedResource "ZeroMQ.libsodium.amd64.so" to "/tmp/ZeroMQ.libsodium.amd64.so".
nunit-agent.exe Information: 0 : UnmanagedLibrary[libzmq] Custom binary "/home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so" not loaded: Failure has occurred while loading a type.
nunit-agent.exe Information: 0 : UnmanagedLibrary[libzmq] Custom binary "/home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so" not loaded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so)
nunit-agent.exe Information: 0 : UnmanagedLibrary[libzmq] Custom binary "/home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so" not loaded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so)
nunit-agent.exe Information: 0 : UnmanagedLibrary[libzmq] Custom binary "/home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so" not loaded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/amd64/libzmq.so)
````

**Comment by sigiesec** [comment]
The Mac OS X build however has only one failing test case, which fails with ():
```
1) Error : ZeroMQTest.ZMonitorTest.Create

System.InvalidOperationException : Canceller SHOULD NOT be null.

  at ZeroMQ.ZThread.Stop () [0x0000e] in <9f80af6f5098446a8c6af2bac576dee7>:0 

  at ZeroMQ.ZThread.Close () [0x00006] in <9f80af6f5098446a8c6af2bac576dee7>:0 

  at ZeroMQ.ZThread.Dispose (System.Boolean disposing) [0x0000b] in <9f80af6f5098446a8c6af2bac576dee7>:0 

  at ZeroMQ.Monitoring.ZMonitor.Dispose (System.Boolean disposing) [0x00025] in <9f80af6f5098446a8c6af2bac576dee7>:0 

  at ZeroMQ.ZThread.Dispose () [0x00000] in <9f80af6f5098446a8c6af2bac576dee7>:0 

  at ZeroMQTest.ZMonitorTest.Create () [0x00017] in <c997de623a984176b3185b7558640161>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <c9f8153c41de4f8cbafd0e32f9bf6b28>:0 

```

The statement that throws this exception was introduced by 9176b6b03aa535924267c8524bb432a3709b83cb

**Comment by metadings** [comment]
That's likely because of Lines 1912 and 1913, Job 104.1, v4.1.0.25, where they say

	$ ./build.sh
	./build.sh: line 13: sw_vers: command not found

And because this is looking for a file `ZeroMQTest.dll` instead of `ZeroMQTest.exe`:

	File not found: /Users/travis/build/zeromq/clrzmq4/ZeroMQTest/bin/Release/ZeroMQTest.dll

Could you please look into this, @sigiesec? I don't know travis-ci.org, appveyor.io or that coverage badge.

**Comment by sigiesec** [comment]
The message regarding sw_vers is only a cosmetic issue. As you can see, the build continues after that message. I will try to suppress it.

You broke the build again by merging #128: After merging #127, https://travis-ci.org/zeromq/clrzmq4/builds/273559047 shows that the jobs are fine (they were cancelled originally because you immediately merged #128 afterwards, but I restarted them), but after merging #128, they fail with the second issue you mentioned above: https://travis-ci.org/zeromq/clrzmq4/builds/273628103

I don't understand your comment regarding "ZeroMQTest.exe". There never was a "ZeroMQTest.exe". The ZeroMQTest.dll contains the NUnit tests that are run with the NUnit test runner (nunit-console.exe).

You also broke the rule again NOT to self-merge!! (A major reason to discourage self merge is to ensure a two-man-rule and check that no CI jobs are broken by the changes, and ideally also to review the changes themselves).

I invested quite a lot of time to get the CI running and to write a number of initial tests. When I started using clrzmq4, there were none. What we have now is the bare minimum for any public library. It is very annoying to see these efforts foiled by careless merges.

Please be more careful about this! Never ever merge a PR if any of the builds is failing! What is even worse is that the new version 4.1.0.25 you tagged is also based on a state where the build failed. 

travis-ci.org (for Linux and Mac OS X) and appveyor.com (for Windows) are both continuous integration services in the cloud. They run builds, and tests and ensure that everything that is committed does not break existing things. They also perform a coverage measurement, that is how much of the code is executed by the tests. clrzmq4 is not yet at a very good coverage level, as you can see. 

They could also be used to publish release packages, so that they come into existence in a traceable way (the build logs are then publicly available and conserved for everyone to see).

**Comment by sigiesec** [comment]
Here, this change obviously causes the failure: https://github.com/zeromq/clrzmq4/compare/a4a6e28f282b...bfffc18595ce#diff-707c4ca7b59acfd50d7e7e4da9f98c4dL4
Why did you remove that!?

**Comment by metadings** [comment]
Ah, because of mixin v4.0 and v4.5.

> sw_vers is only a cosmetic issue. As you can see, the build continues after that message. I will try to suppress it.

No, You don't suppress something. This command is just not available on GNU/Linux, so this is a command on MacOSX. Please look for an alternative, for example `uname`?

> You also broke the rule again NOT to self-merge!! (A major reason to discourage self merge is to ensure a two-man-rule and check that no CI jobs are broken by the changes, and ideally also to review the changes themselves) ... It is very annoying to see these efforts foiled by careless merges.

Please, don't whine about your test methods. They are running fine, if you do some minor changes now. Also with the self-merge: No, I didn't, I was pushing this to metadings and then to zeromq. How would I do an update without doing this?

I'm not careless, I'm just not so shy like you. And I don't care about travis-ci or the like, because I'm running this for myself! So, please, add the Project to the Solution file and look for an alternative of `sw_vars`, `uname` - or what about reading an environment variable - or what about detecting a file, which is just on MacOSX? This would be much better than running an exectuable, each time loading the library.
(for example `/System/Library/CoreServices/SystemVersion.plist`)

**Comment by metadings** [comment]
The problem I have with `ZeroMQTest` is that I can't restore the NUnit package: 

	'NUnit' already has a dependency defined for 'NETStandard.Library'.

And I don't want NETStandard in this library. This is a .NET 4.0 project, without this versioning hell.

**Comment by sigiesec** [comment]
Which version of nuget do you have? I think this is a problem of nuget before 3.4. Can you try updating nuget using ```nuget update -self``` ?

**Comment by sigiesec** [comment]
I will use uname instead of sw_vers

**Comment by metadings** [comment]
No this is not nuget, I do have

	NuGet Version: 4.1.0.2450

**Comment by metadings** [comment]
Oh I'm using MonoDevelop's nuget, v2.8

**Comment by sigiesec** [comment]
Self-merge is about merging your own changes, regardless of the fork in which you committed them.

This is a ZeroMQ organization project, not your private project, so you ought to care about breaking things for others. It is NOT acceptable not to care about the CI builds. In your fork, you can do what you want. But of course it would be great if you submit improvements for the benefit of the community.

**Comment by metadings** [comment]
Yo man, do you really believe others are merging **just if this does not break anything**?

**Comment by metadings** [comment]
I don't know nuget and how to add such a package, which is without NETStandard or NETCore.

Could You please look after `ZeroMQTest` project?
