### ISSUE TITLE
Question: Purpose of code blocking .Net Core operation

### ISSUE THREAD

**Issue by aerotog** [zeromq/clrzmq4#137]
I've been testing a fork of this library that targets .Net Standard 2.0 to use in a couple of .Net Core applications my team owns.

I've managed to get the library to run in .Net Core 2.0 on both Windows and Linux. However, to get it to run in Linux, I have to remove the following code from zmq.cs:

```
// (0) Initialize Library handle (try libsodium.* before libzmq.*)
try { NativeLibSodium = Platform.LoadUnmanagedLibrary(SodiumLibraryName); }
catch (System.IO.FileNotFoundException) { }

// (0) Initialize Library handle
NativeLib = Platform.LoadUnmanagedLibrary(LibraryName);
```

Because the Platform.Posix file is written for Mono, it tries to load and run the __Internal library. Because I'm running in .Net Core, this is not available.

**I understand why it doesn't work when calling the Mono code, but why is this code necessary to begin with? As far as I can tell the "NativeLibSodium" and "NativeLib" variables are not being used anywhere. What is the purpose of setting these variables if they are not used?**

I'm currently looking into .Net Core 2.0 alternatives to the kernel32 "LoadLibrary()" and __Internal "dlopen()" methods. If I find the .Net Core alternative, I may add a new Platform class that uses it. If I get it working, I can probably complete issue #71.

**Comment by metadings** [comment]
These variables are not used, they are just there to have a link to the UnmanagedLibrary, the SafeLibraryHandle and finally the IntPtr.

Important is just once to do Platform.LoadUnmanagedLibrary, which is (simply said) a wrapper around dlopen (in Platform.Posix) / LoadLibrary (in Platform.Win32).

**Comment by aerotog** [comment]
So what happens if it never calls Platform.LoadUnmanagedLibrary? It works without that call or having a link the UnamangedLibrary.

**Comment by metadings** [comment]
No, this library wouldn't work anymore.

How do you load the library in your .NET Core project?

**Comment by aerotog** [comment]
I've forked clrzmq4 into a .Net Standard 2.0 targeting library. The only change I've made is to comment out the "LoadUnmanagedLibrary()" calls.

We have a framework we wrote that implements the [Simple Pirate pattern](http://zguide.zeromq.org/cs:spworker).

We have two applications that are talking to each other via Simple Pirate client/worker.

The applications are running in .Net Core 2.0 on Linux. They work with our fork of the clrzmq4 library where **LoadUnmanagedLibrary is not called**.

It seems the following is sufficient for hooking into the zmq library:
```
[DllImport(LibraryName, EntryPoint = "zmq_msg_init", CallingConvention = CCCdecl)]
private static extern Int32 zmq_msg_init(IntPtr msg);
public static readonly zmq_msg_init_delegate msg_init = zmq_msg_init;
```

Where "LibraryName" is either "libsodium" or "libzmq". I copy the .so archive versions of those libraries into my applications root directories and they run without problem.

**Comment by aerotog** [comment]
I [asked the .Net Core community](https://github.com/dotnet/corefx/issues/24726) for input and they pointed me at "[libdl.so](https://www.unix.com/man-page/All/3lib/libdl/)."

I replaced the Mono "__Internal" hooks with "libdl" and it seems to be working. (Looks like it was changed from "libdl" to "__Internal" back in [March 2016](https://github.com/zeromq/clrzmq4/commit/9c2251370e2ac5608ffe4ed24a1cbed5544bcc28))

After reading up on the [dlopen()](http://man7.org/linux/man-pages/man3/dlopen.3.html) I think I understand the purpose of loading the library into a Safe Handle. I believe it allows for the library to be loaded into memory once (lazily per method because of RTLD_LAZY) and only dereferenced after the Safe Handle is disposed and ReleaseHandle() is called.

Using DllImport without using a Safe Handle does seem to work, but we might see some performance loss/increased memory usage.

@metadings, do you remember why the "libdl" was replaced with "__Internal"? I'd like to make Platform.Posix work whether or not it is running in Mono.

**Comment by metadings** [comment]
Well I did so, because I thought this would always be __Internal...

You should undo this and change it back to libdl!

**Comment by aerotog** [comment]
Okay. I'll test a bit more and open a pull request with the libdl change tomorrow. 

After that I'll probably open a second pull request to target .Net Standard which will be necessary to make the library compatible with Core. That will involve quite a bit more changes but nothing too crazy. It is mainly changes in the csproj file.
