### ISSUE TITLE
PUB / SUB not working when subscriber started before publisher

### ISSUE THREAD

**Issue by richard-shepherd** [zeromq/clrzmq4#141]
The sample code for PUB / SUB does not work when the subscriber is started before the publisher. See this SO question for details: https://stackoverflow.com/questions/47124425/zeromq-pub-sub-not-working-when-subscriber-started-before-publisher

I also saw similar behavior with the REQ / REP samples. The tutorial indicated that they would work when started in either order, but this did not work for me.

**Comment by crosscode-nl** [comment]
I can confirm this. I have the same issue. Taking the library and writing a c++ subscriber, and all works as it should, so the problem must be in the wrapper somehow.

**Comment by danieledallavalle** [comment]
Same problem here!

**Comment by pppop3** [comment]
in .netframework4.5 win7 64bit.
I build 32bit exe   ,reappear  this problem,
the server restarted, clent will not rev the message,  when i connected  server. i have pub/sub

**Comment by K0n63n** [comment]
I also have the same problem. PUB/SUB not working when subscriber is started before publisher, when using version 4.2.3. It works fine with version 4.1.6.

Edit: I'm not using the C# wrapper, so I registered it directly at libzmq

**Comment by flanagak** [comment]
I am also seeing this same issue.  PUB/SUB not working when subscriber is started before publisher, when using version NuGet package v4.1.0.26

**Comment by JohnyL** [comment]
The same thing to me. The manual says that you can start subscriber and then publisher, but I receive no messages.

**Comment by JimmyGong** [comment]
Anyone have the answer?

**Comment by IngFu** [comment]
Is there any chance, that a new package addressing this issue will be pushed to NuGet?

**Comment by metadings** [comment]
[nuget.org/packages/ZeroMQ/4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30)
