### ISSUE TITLE
libzmq.dll missing when deploying with ClickOnce

### ISSUE THREAD

**Issue by alinmotogna** [zeromq/clrzmq4#146]
I wanted to use ZeroMQ.4.1.0.26 nuget in one of my apps that is deployed in production using ClickOnce.
It works fine on my PC, but when I deploy it with ClickOnce, the ZContext or ZSocket constructor just blocks (no error, no exception)
```
            using (context = new ZContext())
            using (subscriber = new ZSocket(context, ZSocketType.SUB))
                      .....
```

When the zmq objects are to be destroyed (app close) it will throw this:
```
System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.IO.FileNotFou
ndException: UnmanagedLibrary[libzmq] Unable to load binary "libzmq" from folders
  ....
 Also unable to load binary from EmbeddedResource "ZeroMQ.libzmq.i386.dll", from temporary path "C:\Users\alin.motogna\AppData\Local\Temp\ZeroMQ.libzmq.i386.dll". See Trace output for more information.
   at ZeroMQ.lib.Platform.Win32.LoadUnmanagedLibrary(String libraryName)
   at ZeroMQ.lib.zmq..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.ZContext..ctor()

```
After some digging I realized that native shared libraries for i386 and amd64 are not copied by ClickOnce, and the workaround I found was to go in [ZeroMQ.targets](https://github.com/zeromq/clrzmq4/blob/master/ZeroMQ.targets) and replace _None_ nodes with _Content_

Can you please take a look at this pull request: https://github.com/alinmotogna/clrzmq4/pull/1

**Comment by VictorSFaria** [comment]
I am interested in this PR, reviewing the code is everything ok. It's possible to PR to official repository?

**Comment by metadings** [comment]
Closing this issue. It's too old
