### ISSUE TITLE
Changing to pgm getting EPROTONOSUPPORT(135): Protocol not supported

### ISSUE THREAD

**Issue by ggeorgiou1** [zeromq/clrzmq4#147]
I am using the web example for pub-sub with envelopes. The below works and see msgs on the Sub side
        using (var publisher = new ZSocket(context, ZSocketType.PUB)) {
                publisher.Linger = TimeSpan.Zero;
                publisher.Bind("tcp://127.0.0.1:5556");

Now when I change code to 
       publisher.Bind("pgm://127.0.0.1:5556"); or 
       publisher.Bind("pgm://127.0.0.1:239.195.195.195"); or
       publisher.Bind("pgm://127.0.0.1;239.195.195.195");
 
getting error 
    EPROTONOSUPPORT(135): Protocol not supported

What am I missing?

Thanks

**Comment by metadings** [comment]
I've removed the openpgm support ... Please do use [ZeroMQ/libzmq](https://github.com/zeromq/libzmq). 

--

Closing this issue. It's too old

**Comment by joao-esteves** [comment]
> I've removed the openpgm support ... Please do use [ZeroMQ/libzmq](https://github.com/zeromq/libzmq).
> 
> --
> 
> Closing this issue. It's too old

Do you mean PGM is no longer supported by clrzmq4? I am having the same problem as the OP but PGM is still listed as supported in the ZeroMQ website.
