### ISSUE TITLE
windows 7 + VS2013 nuget install failure

### ISSUE THREAD

**Issue by Petrox** [zeromq/clrzmq4#15]
Hello!

 The nuget page https://www.nuget.org/packages/ZeroMQ/ tells me to use  "Install-Package ZeroMQ".

 Excepted result:
 "Successfully added...."

 Actual result:

 PM> install-package zeromq
Installing 'ZeroMQ 4.1.0.7'.
You are downloading ZeroMQ from Pieter Hintjens,   metadings, the license agreement to which is available at https://raw.githubusercontent.com/zeromq/clrzmq4/master/LICENSE.txt. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'ZeroMQ 4.1.0.7'.
Adding 'ZeroMQ 4.1.0.7' to ZeroMQ.
Uninstalling 'ZeroMQ 4.1.0.7'.
Successfully uninstalled 'ZeroMQ 4.1.0.7'.
Install failed. Rolling back...
Install-Package : Failed to add reference to 'libsodium'.At line:1 char:1
- install-package zeromq
- ~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

It fails even after 

PM> install-package libsodium-net -Pre
Attempting to resolve dependency 'Baseclass.Contrib.Nuget.Output'.
Installing 'Baseclass.Contrib.Nuget.Output 1.0.7'.
Successfully installed 'Baseclass.Contrib.Nuget.Output 1.0.7'.
Installing 'libsodium-net 0.7.0-beta2'.
You are downloading libsodium-net from adamcaudill, the license agreement to which is available at https://raw.githubusercontent.com/adamcaudill/libsodium-net/master/LICENSE. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'libsodium-net 0.7.0-beta2'.
Adding 'Baseclass.Contrib.Nuget.Output 1.0.7' to ZeroMQ.
Successfully added 'Baseclass.Contrib.Nuget.Output 1.0.7' to ZeroMQ.
Adding 'libsodium-net 0.7.0-beta2' to ZeroMQ.
Successfully added 'libsodium-net 0.7.0-beta2' to ZeroMQ.

I've tried to contact the nuget package owner, but the page tells me to use the project site (linked to this github) to contact the owner.

Also I have tried to download the zeromq windows source zip files:
- 4.1.0 RC - opening the solution gives me error messages that the builds/msvc/properties/Debug.props file is missing (included in the project configuration, but not in the zip files).
- 4.0.5 zip has msvc10 solution only, which needs upgrading when using VS2013, the upgrade happens automatically, but the build fails with 3 xcopy failed with exit code 4 messages.
  
  So I'm stuck, no zeromq install method works as expected, also clrmq 3.0 is a ~2-3 years old beta, and the articles about installation are 3 years old and none works with win7 x64 vs2013 in any ways.

UPDATE: "nuget.exe install zeromq" looks fine ("Successfully installed ZeroMq 4.1.0.7" - even if it's not officially released yet!). I just can't imageine now why visualstudio nuget fails.

**Comment by metadings** [comment]
That seems to be because the libsodium.dll and libzmq.dll are non-MSIL files. Use nuget.exe instead - I'll look into this.

**Comment by arisliang** [comment]
VS2012 has the same error. How to use nuget.exe to install in a solution? Install-package in the Package Management Console in VS has the same error as well.

**Comment by Petrox** [comment]
nuget.exe install ZeroMQ should work, but you will have to download the
standalone exe from nuget website before...

VS2012 has the same issue. How to use nuget.exe to install in a solution?
Install-package in the Package Management Console is not working as well.

**Comment by metadings** [comment]
now i've installed vs2013 and updated the .nuspec file

**Comment by metadings** [comment]
You now need to `Install-Package ZeroMQ`
and set the 'Copy to output directory' property to 'Copy if newer',
on all files in the i386 and amd64 folders.

**Comment by arisliang** [comment]
Thanks, it was a quick fix! Nuget approach working fine on vs12 now.

However, when adding the nuget package to multiple projects, it will create i386 and amd64 folders to all the projects. Changing all their properties is a bit too troublesome, especially when project number grows and all installed the nuget package.

Is it possible to make the default to be "Copy if newer"?

**Comment by metadings** [comment]
Well no, but I'm going to have the files as embedded resource, so there'll be no need to copy the files.

**Comment by petke** [comment]
I'm also having trouble with this. Everything works fine when you install a new project from scratch with nuget etc (setting copy if newer on the files that end up in amd64 and i386). 

But when all non binary files for that project is checked into source control, and checked out into a new local directory then there is trouble. Nuget package restore manages to get ZeroMQ to the packages directory. But it fails to copy any of those files to the project amd64 and i386 folder. I could manually copy them there but thats asking for trouble. 

Anyone got any idea on what is going on?

Edit: One workaround to get new projects checked out of source control to work. Is to uninstall the nuget package, and reinstall it. Then the files end up in amd64 and i386. And you can then do the whole "copy of newer" thing.

**Comment by metadings** [comment]
Yes, you need to `git add -f amd64/libzmq.so` for example, because binary files are ignored by git...
