### ISSUE TITLE
DEALER should block on send if no peer is available

### ISSUE THREAD

**Issue by nickcabral** [zeromq/clrzmq4#153]
From https://rfc.zeromq.org/spec:28/REQREP/
"(DEALER) SHALL block on sending, or return a suitable error, when it has no available peers."

The latest version of clrzmq4 does not match this behavior. If no peers are available, dealer.Send() results in a lost message with no block and no error.

Steps:
- Create a DEALER socket and connect to a port that has no peer.
- Send a message with a ZError out param.
- Observe that the Send() method does not block, and the error is null after the Send() call.

**Comment by VictorSFaria** [comment]
This behaviour is correct the concept of available peer is:
SHALL consider a peer as available only when it has a outgoing queue that is not full.

To do what you want try to set

**Comment by VictorSFaria** [comment]
To do what you expect try the socket option: ZMQ_IMMEDIATE

**Comment by metadings** [comment]
Closing this issue. It's too old
