### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by flanagak** [zeromq/clrzmq4#155]
Just wondering if any of the contributors are still working on this project?
We have not seen any updates for 3+ months now.

Would really like to use this library, but cannot with the existing bugs.

**Comment by kmteam** [comment]
+1 its also important for me, as I'm starting a new project and we would like to use it...

**Comment by sigiesec** [comment]
We are no longer using clrzmq4, at least at the moment, but rather NetMQ, since it added support for CURVE encryption.

**Comment by kmteam** [comment]
Thanks for your answer. I understand then that we should move to NetMq.

**Comment by kmteam** [comment]
Thanks for your answer. I understand then that we should move to NetMq.

Is there any plan to migrate ZMQ C# examples from "The guide" to ZeroMQ?
Is confusing see all C# examples written using clrzmq4 when project is dead and people is moving to NetMQ.

**Comment by sigiesec** [comment]
I think there are some of the examples available at https://github.com/NetMQ/Samples, but maybe not integrated in the zguide. You should raise this question in the NetMQ or zguide project. I guess they would welcome a contribution :) IMO the examples using clrzmq4 should not be removed, but examples using NetMQ should be added along.

**Comment by metadings** [comment]
Well no, this project isn't dead.

I just don't have the time to compile ZeroMQ/zeromq4-1.

I assure you, this is the only problem you do have. I didn't change a single line of code. Just the library loading code - I'm going to revert this.
