### ISSUE TITLE
Got EINTR error when running the service built up using ZMQ

### ISSUE THREAD

**Issue by Hsiaolyn-Zhou** [zeromq/clrzmq4#158]
I got EINTR error when running a test service for a long time, which is using ZeroMQ. (src/../../signaler.cpp line# 249 assert failed.)
I wonder if the code commented out should need or not, the code is inside the ZPollItems.Win32.PollSingle() method as showed below:

                               while (!(result = (-1 != zmq.poll(native, 1, timeoutMs))))
				{
					error = ZError.GetLastErr();

					/* if (error == ZmqError.EINTR) 
					{
						error = default(ZmqError);
						continue;
					} */
					break;
				}

**Comment by metadings** [comment]
Closing this issue. This is related to the source of my native libzmq.dll/.so . Please try the new [nuget.org/packages/ZeroMQ/4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30)
