### ISSUE TITLE
REP bind error

### ISSUE THREAD

**Issue by arisliang** [zeromq/clrzmq4#16]
I used the latest source in the hello world project. For hwserver.cs (https://github.com/imatix/zguide/blob/master/examples/C%23/hwserver.cs), the REP socket's bind statement issues ZException with message {"(100): Address in use"}.

Please help.

**Comment by metadings** [comment]
Well that means you have a program running on that port. Also you can't run Interrupt and HWServer together, because not two programs can bind the same port.
Please change the code to run on another port!

**Comment by arisliang** [comment]
Yesterday, when using F5 in VS to run, it first has the file not found (libzmq.dll) error, then it has Address in use exception. Today F5 in VS consistently has the file not found error.

If rebuild first, then run from debug folder directly instead of inside VS, it seems running fine now.
