### ISSUE TITLE
News on ZeroMQ/clrzmq4 - New Initial Release 

### ISSUE THREAD

**Issue by metadings** [zeromq/clrzmq4#160]
I did `git checkout --orphan master master-new` to create a new commit.

I did so, because there were a few binaries in there, which made the `git clone` around 70 MB.

I've also updated nuget v4.1.0.27 - this time without binary files in i386 and amd64 folders.

You do have to install or build [ZeroMQ/libzmq](https://github.com/zeromq/libzmq) or [/zeromq4-x](https://github.com/zeromq/zeromq4-x).

I'm accepting Pull Requests as of now or if you want, you may do what you do want! @sigiesec

**Comment by bluca** [comment]
@metadings hi - thanks for your work on clrzmq! In general, rewriting history in common repos is a bit frowned upon :-) Is there any chance we could instead start a new repository in the org, and leave this one with the old history, to be more user-friendly?

**Comment by bluca** [comment]
One of the issues is that without git history, all the metadata on user contributions is lost, and given we don't do copyright assignments, this means we can't figure out anymore who are the copyright holders. It might not be an issue now, but in case you want to change or update the license in the future for example, it will become impossible to do so :-(

**Comment by bluca** [comment]
You are doing the work here so it's of course up to you - just a suggestion. Thanks!

**Comment by metadings** [comment]
Look: There are no Copyrights in this project, I've made this LGPL 3 as you can see in [LICENSE.TXT](https://github.com/zeromq/clrzmq4/blob/master/LICENSE.txt).

What would you use as license? I'm not sure, but you can't "change or update" a license at all.

I would prefer now "Public Domain. Gemeinfrei." without Copyright
