### ISSUE TITLE
NuGet v4.1.0.28 does not include i386 and amd64 libs

### ISSUE THREAD

**Issue by jeffdod** [zeromq/clrzmq4#163]
The NuGet v4.1.0.28 package just posted does not include the i386 and amd64 libs like it should. If you pull down this NuGet package into a C# project in Visual Studio 2017, it will build but will crash with an exception on first run. However, the v4.1.0.26 package works as expected.

**Comment by metadings** [comment]
Yes this is so. I've decided you need to install a libzmq binary or you do `git clone https://github.com/zeromq/libzmq` and `make` (or `cmake`) this package.

I've made a hardlink, to have a file name just `libzmq.dll`. You may also rename `libzmq-mt-4_3_1.dll`.
Installed I have this on Windows:

    vcpkg install zeromq:x64-windows

    mkdir C:\projects\clrzmq4\bin\Release\amd64
    mklink /h C:\projects\clrzmq4\bin\Release\amd64\libzmq.dll  c:\Tools\vcpkg\installed\x64-windows\bin\libzmq-mt-4_3_1.dll

on Linux, this is

    sudo apt-get install libzmq5  #  or libzmq3-dev

and on MacOSX (Homebrew)

    brew install zeromq

**Comment by metadings** [comment]
oh - i see, I see if I can make a nuget distro with binaries included...

**Comment by metadings** [comment]
Now please try NuGet v4.1.0.29, which is including libzmq.dll .so and .dylib on x64 and libzmq.dll on x86.

**Comment by jeffdod** [comment]
I still had trouble compiling with 29, but not 26.

Also, can 0MQ be used with.Net Core?

**Comment by kristanbbc** [comment]
Hi, .29 still doesn't build for me, but 26 does.

**Comment by metadings** [comment]
What's the problem with .29, could you please tell me an error, a message?

**Comment by jeffdod** [comment]
Hi,

I created a new C#.NET console app using .NET Framework 4.6.1 in Visual
Studio 2017, then added the 4.1.0.29 NuGet package for ZeroMQ. When I
compile, I get the following errors:

Error Could not copy the file
"E:\Projects\ZMQTest\packages\ZeroMQ.4.1.0.29\build\i386\libzmq.dylib"
because it was not found.
Error Could not copy the file
"E:\Projects\ZMQTest\packages\ZeroMQ.4.1.0.29\build\i386\libzmq.so" because
it was not found.

**Comment by kristanbbc** [comment]
To confirm I was having the same error as Jeff.

**Comment by metadings** [comment]
I've packed a new nuget package v4.1.0.30 - please try this one.

**Comment by metadings** [comment]
Closing this issue. Please try [nuget.org/packages/ZeroMQ/4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30)
