### ISSUE TITLE
latest v4.1.0.30 not include libsodium.dll while create instance

### ISSUE THREAD

**Issue by slmgong** [zeromq/clrzmq4#165]
UnmanagedLibrary[libsodium] Unable to load binary "libsodium" from folders
	C:\WINDOWS\system32\libsodium.dll
  ....

**Comment by metadings** [comment]
Please look into [zeromq/clrzmq4/commit/ed682a](https://github.com/zeromq/clrzmq4/commit/ed682a99f1030ac398be00010157248d7565a785)
