### ISSUE TITLE
RRBroker: ZException: EFAULT(14): Bad address

### ISSUE THREAD

**Issue by arisliang** [zeromq/clrzmq4#18]
var frontend = ZSocket.Create(context, ZSocketType.ROUTER);

has a following exception:
EFAULT(14): Bad address
   at ZeroMQ.ZSocket..ctor(ZContext context, ZSocketType socketType)
   at ZeroMQ.ZSocket.Create(ZContext context, ZSocketType socketType)

The code is basically following http://zguide.zeromq.org/cs:rrbroker, not sure if it's useful, but I started the broker in its own thread. I wanted to suspect if it was the endpoint string problem, but it seems this exception happened even before passing any endpoint to the socket.

**Comment by metadings** [comment]
This exception occurs only if you didn't supply a valid endpoint identifier.

**Comment by arisliang** [comment]
I think it's not because of endpoint. Actually, I commented out the rest of the code, so Socket.Create is the only one left. It will still give the same error.

Below is my test code, if it starts in own thread, it gives exception "EFAULT(14): Bad address". Interestingly, if I start the code in the main thread, the exception is gone.

```
    static void Main(string[] args)
    {
        using (var context = ZContext.Create())
        {
            bool ownThread = false;
            if (ownThread)
            {
                // No exception
                var frontend = ZSocket.Create(context, ZSocketType.ROUTER);
            }
            else
            {
                // Bad address exception
                var broker = new Thread(
                   () =>
                   {
                       ZSocket.Create(context, ZSocketType.ROUTER);
                   });
                broker.Start();
            }
        }
    }
```

**Comment by metadings** [comment]
This code kills `context`, most likely before the new socket is created. You'll need something like `Thread.Sleep` after `broker.Start()`.

Also I suggest you to use `ZSocket.Create(context, ZSocketType.Router, out error)`, instead of catching the exception...

**Comment by arisliang** [comment]
After adding Thread.Sleep, it's fine. Noted the suggestion as well. Thanks a lot.
