### ISSUE TITLE
Unhandled Exception of type 'System.TypeInitializationException' occured in ZeroMQ.dll

### ISSUE THREAD

**Issue by tuldok89** [zeromq/clrzmq4#19]
![capture](https://cloud.githubusercontent.com/assets/854884/6571181/09565742-c740-11e4-8b2e-283685182700.PNG)

So I tried running the HWClient sample using the latest ZeroMQ nuget package. I've tried compiling it for both .net 4.0 and .net 4.5, and the results are the same. 

Upon the instantiation of ZContext, TypeInitializationException gets thrown.

The inner exception is: {"UnmanagedLibrary[libzmq] Unable to load library \"libzmq\" from
\"C:\TEMP\libzmq.dll\". Inspect Trace output for details.":"C:\TEMP
\libzmq.dll"}

**Comment by tuldok89** [comment]
Even a minimal test case like the one below is throwing the same error.

```
using System;
using ZeroMQ;

namespace TestCase
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new ZContext())
            {

            }
        }
    }
}
```

**Comment by metadings** [comment]
Please set the files in `i386` and `amd64` to "copy if newer" (`.dll` for Windows and `.so` for Linux).

**Comment by tuldok89** [comment]
Thanks, it solved the issue.

I didn't expect that :) I guess I'm used to some NuGet packages that automatically copies the native DLLs to the build folder.

**Comment by metadings** [comment]
Yeah, sadly isn't that for native dlls... I'll have to make them embedded resources, however that will give some weight to the binary...

**Comment by metadings** [comment]
The examples are cool right? I like Espresso...:

```
01410000000000000000
01420000000000000000
B 29804bd50000000000
B 69abb4530000000000
A e13169fe0000000000
B 48fe8c100000000000
B 8d64be370000000000
I: subscriber counted 5
00410000000000000000
00420000000000000000
```

**Comment by tuldok89** [comment]
Yeah, the examples are nice :+1: I've just started learning ZeroMQ, and I prefer this lib, over the pure CLR one, since it's much closer to the C API.

Anyway... IIRC the approach used by the SQL Server compact NuGet package is that, it executes a powershell script to automatically copy the native binaries to the build folder. They're not embedded resources, I think.

**Comment by metadings** [comment]
Thanks :+1:

I'll have to look into the SQL Server compact package!

**Comment by floradu88** [comment]
Thanks, this issue is solved by the above answer: "Please set the files in i386 and amd64 to "copy if newer" (.dll for Windows and .so for Linux)."

**Comment by super999** [comment]
Thanks, this issue is solved by the above answer: "Please set the files in i386 and amd64 to "copy if newer" (.dll for Windows and .so for Linux)."  +1

**Comment by metadings** [comment]
:green_apple: :green_heart: :cool: :recycle: :+1:

**Comment by jugalpanchal** [comment]
This is a very silly problem. The answer is perfect. It solved my problem.
Thank you so much! :+1:

**Comment by oriolorra** [comment]
I have the same problem..... What do you mean with  "Please set the files in i386 and amd64 to "copy if newer" (.dll for Windows and .so for Linux)."? I do not know how to proceed.

Thanks,

**Comment by metadings** [comment]
I'm sorry, I don't know how to say this otherwise, you should try harder.

"Please copy the folders i386 and amd64 into the project's output directory."

You should end up using a directory structure like this one:

	\MyProject
		\bin
			\Debug
				\amd64
					\libzmq.dll
					\libzmq.so
				\i386
					\libzmq.dll
					\libzmq.so
				\MyProject.exe
				\ZeroMQ.dll
		\amd64
			\libzmq.dll
			\libzmq.so
		\i386
			\libzmq.dll
			\libzmq.so
		\AssemblyInfo.cs
		\Program.cs

**Comment by Glaemyr** [comment]
So, I know that this is an old question, but what could be the cause and possibly fix when the inner exception is not "UnmanagedLibrary" but a NullReferenceException?
I'm trying to create a ZContext in the OnStart() method of a windows service and get the TypeInitializationException when trying to call new ZContext().

I aldready copy the amd64 and i386 folders to the output folder and I have ZeroMQ installed using NuGet.
If I create the context in a test and pass it to the class that needs to use it, it works without any complications.

Again sorry for reopening the issue, but I really am at my wits end.
