### ISSUE TITLE
ZSocket.ReceiveBytes should return int instead of bool

### ISSUE THREAD

**Issue by ghost** [zeromq/clrzmq4#20]

**Comment by metadings** [comment]
You're right, I didn't use the `ReceiveBytes` method anywhere, it depends on `zmq_recv`. I need to return the length of bytes which were actually received.

There should also be a `ReceiveBytes` method which doesn't rely on an existing byte buffer, but returns a `new byte[xyz]` where xyz is the length of bytes in a ZFrame (using `zmq_msg_recv`).
