### ISSUE TITLE
Send/Receive Buffer Size always 0 and HWM issue

### ISSUE THREAD

**Issue by graham83** [zeromq/clrzmq4#25]
I have a binded PUB socket in one task and a connected SUB socket in a separate task in the same ZContext / process - using the inproc protocol - they are talking fine, and if I sleep the SUB task I can see the PUB task sending regardless, and then the SUB task catches up. When the PUB task is obviously buffering while the SUB task is a asleep  (I am sending a queue of 100000 messages in a loop) - the pubSocket.SendBufferSize remains at zero - and the subSocket.ReceiveBufferSize remains at zero which does not seem right.

Furthermore - setting the HWM (before Binding or Connecting) is having no effect - if I set PUB HWM to 100 for instance, and publish 10000 messages in 10 seconds (sleep for 1ms between sends), and sleep the SUB task this whole time - I still receive ALL the messages when the SUB socket resumes receiving - even though both send and receive buffer size remain at zero - ie No messages are being dropped.  Ultimately I think this is what is causing grief in the application problem I am trying to solve.

There are no HWM examples or examples using ReceiveBufferSize/SendBufferSize - so can someone please throw me a bone and confirm that this very recent release does not have issues in this area and / or provide me with an example.

This is my first involvement with zmq and github in general so let me know if I am going about getting answers / assistance the wrong way.

**Comment by metadings** [comment]
I'm going to rebuild the [metadings/zguide/psenvpub](https://github.com/metadings/zguide/blob/master/examples/C%23/psenvpub.cs) and [metadings/zguide/psenvsub](https://github.com/metadings/zguide/blob/master/examples/C%23/psenvsub.cs) examples, to see how much was `int published` and `int subscribed`.

The `ZSocket.SendBufferSize` and `ZSocket.ReceiveBufferSize` are properties of the socket, and I don't expect them to change.

Have a look into the [docs on `zmq_getsockopt`](http://api.zeromq.org/4-1:zmq-getsockopt#toc28):

```
ZMQ_RCVBUF: Retrieve kernel receive buffer size

The ZMQ_RCVBUF option shall retrieve the underlying kernel receive buffer size 
for the specified socket. A value of zero means that the OS default is in effect.
For details refer to your operating system documentation for the SO_RCVBUF socket option.

Option value type   int
Option value unit   bytes
Default value   0
Applicable socket types     all
```

**Comment by graham83** [comment]
Thank you - and i understand - ReceiveBufferSize / SendBufferSize is not going to give me any confirmation of the send/receive HWM.  

EDITED: Performance Profiler showed obvious mistake in previous test code posted, reporting slow pub / sub - Console Write Line was the delay. Now getting > 200 000 msgs/sec now. Live and learn.

**Comment by metadings** [comment]
Wow :)

You previous test code isn't live anymore... However you may "unlock" the Main thread using

```
while (true) Thread.Sleep(1000);
```
