### ISSUE TITLE
Required types for secure messaging are missing

### ISSUE THREAD

**Issue by james-cxx** [zeromq/clrzmq4#26]
Security types, such as zauth, appear to be missing from clrzmq4.  It does not seem possible to implement the Iron House example with clrzmq4: http://hintjens.com/blog:49

**Comment by metadings** [comment]
No, the `zauth`-like syntactic sugar is currently not in clrzmq4.

Please look into the [`ZSocket class`](https://github.com/zeromq/clrzmq4/blob/master/ZSocket.cs#L1189).
You can use the socket options to run ZeroMQ on a CURVEd socket. 
There are `bool ZSocket.CurveServer`, `byte[] ZSocket.CurveSecretKey`,
`byte[] ZSocket.CurvePublicKey` and `byte[] ZSocket.CurveServerKey`.

**Comment by james-cxx** [comment]
Works like a charm.  Thanks metadings!

**Comment by metadings** [comment]
:+1:

**Comment by deanroker123** [comment]
Hi metadings,

I am looking to implement this too, will zauth be in the bindings eventually? 

How can you generate new keys to be used and saved?

Sorry if they are stupid questions, I am not that experienced at development.

Thanks

**Comment by metadings** [comment]
wow hey, the ZAuthentication classes will take some time...

The `privateKey` of an authentication you get using a random number generator:

```
var privateKey = new byte[32];
using (var rng = new RNGCryptoServiceProvider()) rng.GetBytes(privateKey);
```

you could now calculate the `publicKey` using...

```
var publicKey = new byte[32];
crypto.box_keypair(publicKey, privateKey);
```

... if you use some library like [jedisct1/libsodium](https://github.com/jedisct1/libsodium/)!

**Comment by deanroker123** [comment]
Hi Uli,

Thanks for the info, I will look into libsodium, it seems like a very
interesting library.

That should give me enough to get me going.

Unfortunately I'm  not confident enough to be able to help with the zauth
work. I have never wrapped a c library in c# and wouldn't now where to
begin.

One other question. Is there anyway to convert a z frame directly to a
byte[]?

Thanks

Dean

**Comment by metadings** [comment]
Yes, using 

```
frame.Position = 0;
byte[] bytes = (ZFrame)frame.Read();
```

That's actually [a very new method](https://github.com/zeromq/clrzmq4/commit/6a9c42246989e1672be55dc7cf49a53cba8a2f7a), you need to `git pull origin master` or just download the zip file.

I am going to post myself a crypto library `tweetnacl.c` and `TweetNaCl.CSharp` ... wait some hours!

**Comment by robreeves** [comment]
Could a curve example be added to https://github.com/metadings/zguide please? As someone not that familiar with curve this gives me some good clues to get started, but a hello world example with curve security would help a ton. Thanks!

**Comment by metadings** [comment]
@rr118 you should open a new issue, I'm going to close this one...
