### ISSUE TITLE
Actor automatic endpoint generation can result in invalid endpoints

### ISSUE THREAD

**Issue by Haewk** [zeromq/clrzmq4#27]
It seems like the code generating the actor endpoint sometimes generate an invalid endpoint. From the testing I did this seems to occur when the generated byte array starts with a zero which is converted to "\0" by the encoder and triggers the error.

In the ZActor constructor code:

```
        var rnd0 = new byte[8];
        using (var rng = new System.Security.Cryptography.RNGCryptoServiceProvider()) rng.GetBytes(rnd0);
        this.Endpoint = string.Format("inproc://{0}", ZContext.Encoding.GetString(rnd0));
```

Converting a random bunch of bytes using Encoding is dangerous I think. Using the BitConverter instead seems to solve the problem:

```
        this.Endpoint = string.Format("inproc://{0}", BitConverter.ToString(rnd0));
```

Here is some unit test code to trigger the problem with a repeat count of 500. Not guaranteed to trigger it but if you run the test a few times or increase the repeat count you are sure to bump into it. The code commented out implements the BitConverter fix described above and manually specifies the endpoint.

```
        using (var context = ZContext.Create())
        {
            for (var i = 0; i < 500; i++)
            {
                //var rnd0 = new byte[8];

                //using (var rng = new System.Security.Cryptography.RNGCryptoServiceProvider())
                //    rng.GetBytes(rnd0);

                //var ep = string.Format("inproc://{0}", BitConverter.ToString(rnd0));
                //var actor = new ZActor(context, ep, (ctx, skt, clr, args) => { });

                var actor = new ZActor(context, (ctx, backend, cancellor, args) => { });

                try
                {
                    actor.Start();
                }
                catch (ZException ze)
                {
                    var problem = actor.Endpoint.Substring(9);
                    var bytes = ZContext.Encoding.GetBytes(problem);

                    throw new Exception(string.Format("Exndpoint - {0} ({1})", actor.Endpoint, BitConverter.ToString(bytes)), ze);
                }
                finally
                {
                    actor.Dispose();
                }
            }
        }
```

**Comment by metadings** [comment]
I don't have problems... Look into FLCliApi and SuiSnail examples where ZActor is used, they are working like a charm, don't they?

**Comment by Haewk** [comment]
FLCliApi and SuiSnail do not create a lot of ZActors. I normally do not run into the issue before the 80th ZActor created which is why I provided a unit test that creates 500 actors which will almost always result in a failure.

I am running on Win7 32-bit but I think I also tested the issue on Win7 64-bit.

**Comment by metadings** [comment]
Please, can you look what bytes there are used as identity?

**Comment by metadings** [comment]
Hello! As expected, it was the `00` bytes in the identity. I'm now using [`RNG.GetNonZeroBytes`](https://github.com/zeromq/clrzmq4/blob/master/ZActor.cs#L23).
