### ISSUE TITLE
Mapping of ZContextOption wrong

### ISSUE THREAD

**Issue by gillima** [zeromq/clrzmq4#28]
The definition of the ZContextOption enum is different from the values in libzmq.

``` cpp
#define ZMQ_IO_THREADS  1
#define ZMQ_MAX_SOCKETS 2
```

``` csharp
public enum ZContextOption
{
    IO_THREADS,
    MAX_SOCKETS,
    IPV6
}
```

To reproduce use following code (where as 1024 is the default value for max sockets):

``` csharp
System.Diagnostics.Debug.Assert(zcontext.MaxSockets == 1024);
```

**Comment by metadings** [comment]
I wouldn't expect to have `ctx.MaxSockets == 1024`... 
And I don't see the hard difference, `IO_THREADS == 1` and `MAX_SOCKETS == 2`

**Comment by gillima** [comment]
The problem is that C# enums start with 0, so IO_THREADS == 0.
When you set zcontext.MaxSockets = 5, it will set IO_THREADS = 5 on the underlaying socket.

**Comment by metadings** [comment]
OH, I'm going to change that ;)

**Comment by metadings** [comment]
This is changed now.
