### ISSUE TITLE
EAGAIN Exception Rasied not sure it should be

### ISSUE THREAD

**Issue by deanroker123** [zeromq/clrzmq4#29]
Hi,

I copied the Example of the PollIn method but the ZError doesn't seem to be populated it throws a real exception instead.

serverSocket is a Rep socket.

The output of the Exception is 
 EAGAIN(11): Resource temporarily unavailable

Any ideas what I did wrong. I would have expected it to not throw an exception but to have filled the error variable populated.

Thanks

Dean

public void MainServerLoop()
        {
            log.Debug ("Starting The server Loop");
            var poll = ZPollItem.CreateReceiver();
            ZMessage value;
            ZError error;
            while (true) {
                log.Debug ("Waiting for Message");
                try{
                if (serverSocket.PollIn (poll, out value, out error, TimeSpan.FromMilliseconds (64))) {
                    log.Debug ("Message There");
                    ZMessage response = ProcessMessage (value);
                    serverSocket.SendMessage (response);
                } else {
                    if (error == ZError.ETERM)
                        log.Debug ("ETERM Error");
                        //return;    // Interrupted
                    if (error != ZError.EAGAIN)
                        log.Debug ("EAGAIN Error");
                        throw new ZException (error);
                    log.Debug ("No Message Found");
                    }
                } catch (Exception e){
                    log.Debug ("There was an Exception");
                    log.Debug (e);
                }
            } 
            log.Debug ("Exited the MainSeverLoop");
        }

**Comment by metadings** [comment]
```
public void MainServerLoop()
{
    log.Debug ("Starting The server Loop");
    var poll = ZPollItem.CreateReceiver();
    ZMessage value;
    ZError error;
    while (true) {
        log.Debug ("Waiting for Message");
        if (serverSocket.PollIn (poll, out value, out error, TimeSpan.FromMilliseconds (64))) {
            log.Debug ("Message There");
            ZMessage response = ProcessMessage (value);
            serverSocket.SendMessage (response);
        } else {
            if (error == ZError.ETERM)
                log.Debug ("ETERM Error");
            if (error != ZError.EAGAIN) { // missing {
                log.Debug ("EAGAIN Error");
                throw new ZException (error);
            } // missing }
            log.Debug ("No Message Found");
        }
    }
    log.Debug ("Exited the MainSeverLoop");
}
```

You are just missing two brackets `{ }`....

**Comment by deanroker123** [comment]
Im so sorry, school boy error.

The conversion form NetMQ to ZeroMQ has been a tricky one.

Thanks for the pointer.

Thanks

Dean

**Comment by metadings** [comment]
:+1:
