### ISSUE TITLE
SendFrame method in ZSocket disposes of ZFrame even if error = EAGAIN

### ISSUE THREAD

**Issue by koren99** [zeromq/clrzmq4#31]
the code does frame.Dismiss in the finally clause, which does not seem right to me.
from my tests it does seem the message is stable when EAGAIN is returned and i can resend the message.
though the documentation in zmq is not completely clear, it does stand to reason that the message will be dismissed and nullified when the method succeeds and not on EAGAIN.
thoughts?

**Comment by metadings** [comment]
Yes, I didn't care about (re-)sending, however the one or two try blocks in clrzmq4 are going to be removed...

**Comment by metadings** [comment]
You need now release v4.1.0.16 from nuget or [github](https://github.com/zeromq/clrzmq4/releases), which includes [a commit](https://github.com/zeromq/clrzmq4/commit/c5611661d65607b14f002a32aef8c6f8b0ecac00) to remove the try...catches.
