### ISSUE TITLE
Static Constructor and Static Variable for Context

### ISSUE THREAD

**Issue by mahald** [zeromq/clrzmq4#35]
Hi,

Just wondering why u are not using a Static Constructor and Static Variable for the Context.
It could be as easy as: 

```
    static ZContext _context; // static = accessable for any instance

    // static constructor = called before first instanciation only
    static ZSocket()
    {
     _context = new ZContext();
    }

    public ZSocket(ZSocketType socketType)
    {
        _socketType = socketType;

        ZError error;
        if (!Initialize(out error))
        {
            throw new ZException(error);
        }
    }
```

And no one would have to care about the context anymore. You don't have to passe it to other Thread, as it just is there.
Or are there any reasons to instantiate 2 Contexts ?
Just my 2 cents.

**Comment by metadings** [comment]
You're right, but you are fixing the problem too hard. We need something like

```
private static ZContext _current;

public static ZContext Current {
    get {
        if (_current == null) _current = new ZContext();
        return _current;
    }
}
```

So... there MAY be a reason to create two or more contexts.

**Comment by metadings** [comment]
Using `git pull zeromq master`, you now have `new ZSocket(ZSocketType socketType)` !

**Comment by metadings** [comment]
I've made a new [ZeroMQ/clrzmq4 release](https://github.com/zeromq/clrzmq4/releases), which is using `ZContext.Current`, so you can do `new ZSocket(ZSocketType socketType)`.
