### ISSUE TITLE
Setting encryption keys

### ISSUE THREAD

**Issue by zattil** [zeromq/clrzmq4#37]
I am trying the library and I would like to request some help.

I am using router socket and trying to set encryption keys. I have 40 characters long encryption keys. 
Using Z85 to decode and set the keys.

 var keybytes = ZeroMQ.Z85.ToZ85DecodedBytes("key")
socket.CurveSecretKey = keybytes;

I set CurveSecretKey, CurvePublicKey,  CurveServerKey but when I try to access these keys it gives this error "EINVAL(22): Invalid argument".

The communication between the client app and my router socket doesn't work. If  we don't use encryption keys the the communication works. The decoded bytes I am using should be correct they are used in other implementations (not .net)

Thanks.

**Comment by gillima** [comment]
The problem seems to be with the data type of the keys. We use curve for our connections and they work fine when we use `ZSocket.SetOption(ZSocketOption.CURVE_...` instead of the properties.
Here the example using the test keys from the zmq page:

``` csharp
         this.FrontendSocket.SetOption(ZSocketOption.CURVE_SERVERKEY, @"rq:rM>}U?@Lns47E1%kR.o@n%FcmmsL/@{H8]yf7");
         this.FrontendSocket.SetOption(ZSocketOption.CURVE_PUBLICKEY, @"Yne@$w-vo<fVvi]a<NY6T1ed:M$fCG*[IaLV{hID");
         this.FrontendSocket.SetOption(ZSocketOption.CURVE_SECRETKEY, @"D:)Q[IlAW!ahhC2ac:9*A}h:p?([4%wOTJ%JR%cs");
```

Maybe you are aware of this, but be careful with the keys when you paste them for test in your code. When they contain `{` you must either use the `@` in front of the string or escape the `{` as `{{`...

**Comment by metadings** [comment]
YEAH... you are right, as long as you are hard-coding these keys... If you have them in a `byte[]`, say from reading from a file, you don't need to escape `char[]` sequences...

**Comment by metadings** [comment]
This is like `"key".ToZ85DecodedBytes()`...
You are just getting `byte[3]` from `new char[3] { 'k', 'e', 'y' }`... And this is `EINVAL`id...

You should have instead `byte[32]` from your key data, so you need something like

```
var privateK = new byte[32];
var publicK = new byte[32];

// make Private key 
using (var rng = new RNGCryptoServiceProvider()) rng.GetBytes(privateK);

// get Public key
crypto.scalarmult_base(publicK, privateK);

socket.SetOption(ZSocketOption.CURVE_SECRETKEY, privateK);
socket.SetOption(ZSocketOption.CURVE_PUBLICKEY, publicK);
// ...
```

then you also can move your `byte[]` around with `Z85.Encode`...
