### ISSUE TITLE
can this dll be used in xp 32bit computer with .net framework 4.0

### ISSUE THREAD

**Issue by heyxEvget** [zeromq/clrzmq4#49]
hi，
    I use this dll in my project on xp 32 bit whit .net framewok4.0, but my project is always warming that the dll reflects defeated. could you please tell me how to solve this problem ?

**Comment by metadings** [comment]
You can replace the files in folders `i386` and `amd64`...

```
i386\libzmq.dll
i386\libzmq.so
i386\libsodium.dll
i386\libsodium.so
amd64\libzmq.dll
amd64\libzmq.so
amd64\libsodium.dll
amd64\libsodium.so
```

... with the one, you want to use! ZeroMQ/clrzmq4 just needs a version > v4.0. `libsodium` is optional.

Basically you may also use the VERY OLD COPY on [zeromq.org](http://zeromq.org/intro:get-the-software).
