### ISSUE TITLE
Cannot load .so/.dylib file on Mono/MacOSX/libzmq

### ISSUE THREAD

**Issue by tomwinans** [zeromq/clrzmq4#51]
Hi

When I use the nuget package on linux I get the following exception. For some reason it is looking in /var for the .so file. I am using this on OSX with Mono and find the same problem, though "copy if newer" and "always copy" do not resolve. Here is what I get when I put the lib...{dll&so} in the folder named here:

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.IO.FileNotFoundException: UnmanagedLibrary[libzmq] Unable to load library "libzmq" from "/var/folders/jm/vkm98mmn2pq6gj6ysc3b3xwm0000gn/T/libzmq.so". Inspect Trace output for details.
File name: '/var/folders/jm/vkm98mmn2pq6gj6ysc3b3xwm0000gn/T/libzmq.so' ---> System.DllNotFoundException: dlopen(/var/folders/jm/vkm98mmn2pq6gj6ysc3b3xwm0000gn/T/libzmq.so, 257): no suitable image found.  Did find:
    /var/folders/jm/vkm98mmn2pq6gj6ysc3b3xwm0000gn/T/libzmq.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00
  at ZeroMQ.lib.Platform+Posix.LoadUnmanagedLibrary (System.String libraryName) [0x00213] in /Users/tommy/Downloads/clrzmq4-master/lib/Platform.Posix.cs:123 
  at ZeroMQ.lib.zmq..cctor () [0x005b6] in /Users/tommy/Downloads/clrzmq4-master/lib/zmq.cs:40 
  --- End of inner exception stack trace ---
  at ZeroMQ.ZContext..ctor () [0x00007] in /Users/tommy/Downloads/clrzmq4-master/ZContext.cs:55 
  at Examples.Program.Main (System.String[] args) [0x00008] in /Users/tommy/Projects/ZMQ_Example/ZMQ_Example/Program.cs:170

**Comment by metadings** [comment]
See also [`metadings comment on Feb 10, 2016`](https://github.com/zeromq/clrzmq4/issues/36#issuecomment-182195622)

**Comment by metadings** [comment]
hehe... closing this too early... you say you have MacOSX

**Comment by metadings** [comment]
You need a `git pull origin master` or `git clone https://github.com/zeromq/clrzmq4` ...
and rebuild the package to try the new [`lib/Platform.cs`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.cs#L160)

```
namespace ZeroMQ.lib {  // ...

public static partial class Platform {  //...

    static Platform() { // ...

        IsMonoMac = assemblies.Any(a => a.GetName().Name.Equals("MonoMac", StringComparison.InvariantCultureIgnoreCase));

        if (IsMonoMac) {
            Kind = PlatformKind.Posix;
            Name = PlatformName.MacOSX;
        }

    // ...
    public static bool IsMonoMac { get; private set; }

    // ...
```

**Comment by metadings** [comment]
Look: The directives

```
Platform.Kind = PlatformKind.Posix;
Platform.Name = PlatformName.MacOSX;
```

just mean this will override by [`class Platform.Posix`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Posix.cs) and then by [`class Platform.MacOSX`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.MacOSX.cs).

**Comment by tomwinans** [comment]
will try this... thanks...

**Comment by metadings** [comment]
Hey! I've made a new [ZeroMQ/clrzmq4 release](https://github.com/zeromq/clrzmq4/releases) also available on nuget.

You should now get an exception, that instead of a `.so`, a `.dylib` file is missing... I can't make such a dylib file because I don't have a Mac... However, you can make one, then put the file into the `amd64` folder.
I'm open for publishing a `.dylib` file, you just need to make `libzmq (v4.1)` with `libsodium` and `openpgm` - and tell me which compiler version you used.

**Comment by metadings** [comment]
On Linux and also for MacOSX systems, I've updated the code to properly load files from, for example

```
[0]: "/home/metadings/zguide/examples/C#/bin/Debug/amd64/libsodium.so.*"
[1]: "/home/metadings/zguide/examples/C#/bin/Debug/x64/libsodium.so.*"
[2]: "/home/metadings/zguide/examples/C#/bin/Debug/amd64/libsodium.so"
[3]: "/home/metadings/zguide/examples/C#/bin/Debug/x64/libsodium.so"
[4]: "/usr/lib/x86_64-linux-gnu/libfakeroot/libsodium.so.*"
[5]: "/usr/lib/i386-linux-gnu/mesa/libsodium.so.*"
[6]: "/lib/i386-linux-gnu/libsodium.so.*"
[7]: "/usr/lib/i386-linux-gnu/libsodium.so.*"
[8]: "/usr/local/lib/libsodium.so.*"
[9]: "/lib/x86_64-linux-gnu/libsodium.so.*"
[10]: "/usr/lib/x86_64-linux-gnu/libsodium.so.*"
[11]: "/usr/lib/x86_64-linux-gnu/mesa-egl/libsodium.so.*"
[12]: "/usr/lib/x86_64-linux-gnu/mesa/libsodium.so.*"
[13]: "/usr/lib/x86_64-linux-gnu/libfakeroot/libsodium.so"
[14]: "/usr/lib/i386-linux-gnu/mesa/libsodium.so"
[15]: "/lib/i386-linux-gnu/libsodium.so"
[16]: "/usr/lib/i386-linux-gnu/libsodium.so"
[17]: "/usr/local/lib/libsodium.so"
[18]: "/lib/x86_64-linux-gnu/libsodium.so"
[19]: "/usr/lib/x86_64-linux-gnu/libsodium.so"
[20]: "/usr/lib/x86_64-linux-gnu/mesa-egl/libsodium.so"
[21]: "/usr/lib/x86_64-linux-gnu/mesa/libsodium.so"
```

Please do a  `git pull zeromq master` to try the changes.

I do need new binaries for the `i386`, `amd64` folders. Would you like to make the `dylib` file?

**Comment by metadings** [comment]
I've made the update v4.1.0.20... Let's try. (Oh, you're on MacOSX... You need a `dylib` file.)

**Comment by metadings** [comment]
I do want to close this issue, because I changed to lookup for the `.dylib` on MacOSX in [multiple folders on Posix](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Posix.cs#L25).

However, I don't know about the issue, because I don't have a Mac. 

Please create such a `.dylib` file in xcode, using `libzmq`, `libsodium` and possibly `libpgm`.
Then go forking this project `ZeroMQ/clrzmq4`, call `git add -f amd64/libzmq.dylib` and send me a PR!

Now I'm also using a method [`EnumerateLibLdConf`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Posix.cs#L213) which enumerates `ld.so.conf`;
with the directive `include /etc/ld.so.conf.d/*.conf`, the method also looks into folders `/lib/`, `/usr/lib/`, `/usr/local/lib/` etc.

**Comment by metadings** [comment]
May I ask you, if you have a `/etc/ld.so.conf` at all?

If you don't have this file, I need to update LibraryPaths to the default `.dylib` search paths.

**Comment by sigiesec** [comment]
I added CI for Mac OS X via #104. I needed to do some changes in the library loading code to get this to run. I install libzmq via MacPorts there, see the build.sh script.

Can you try that version, and see if it works in your environment?

**Comment by metadings** [comment]
Closing this issue. It's too old
