### ISSUE TITLE
Is ZeroMQ.dll version decreased?

### ISSUE THREAD

**Issue by goldenbull** [zeromq/clrzmq4#55]
I had a project which installed ZeroMQ 4.1.0.17 by nuget on 2016-01-15, in the .csproj file these new lines were added:

```
    <Reference Include="ZeroMQ, Version=4.1.0.42169, Culture=neutral, PublicKeyToken=4a9630883fd6c563, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\ZeroMQ.4.1.0.17\lib\net40\ZeroMQ.dll</HintPath>
    </Reference>
```

I created a new project today and install ZeroMQ 4.1.0.19 by nuget. When I use this new project to communicate with the old project, I got and exception when calling `ZFrame.ReadString`:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt
```

Then I dive into this bug and find that in the new project the ZeroMQ.dll has a smaller version number:

```
    <Reference Include="ZeroMQ, Version=4.1.0.20957, Culture=neutral, PublicKeyToken=4a9630883fd6c563, processorArchitecture=MSIL">
      <HintPath>..\..\packages\ZeroMQ.4.1.0.19\lib\net40\ZeroMQ.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

So there is a number reversal: package 4.1.0.17 has a DLL 4.1.0.42169 and package 4.1.0.19 has a DLL 4.1.0.20957
In the new project, I referenced to the ZeroMQ.dll 4.1.0.42169 in 4.1.0.17 manually, and the exception is gone.
Seems there is something wrong with the ZeroMQ.dll in 4.1.0.19?

**Comment by goldenbull** [comment]
Further investigation shows that this version reversal happens when 4.1.0.17 --> 4.1.0.18

**Comment by goldenbull** [comment]
I see some code changes in `ZFrame.cs` from 4.1.0.17 to 4.1.0.18, which may introduce incompatibility and cause the exception.

So there are actually two issues here:
1. Version number reversal, which seems to be a small mistake
2. Incompatibility between 4.1.0.17 and 4.1.0.18, which seems to be a feature by design.

**Comment by metadings** [comment]
Yes, the Version number is determined by VisualStudio/MonoDevelop (which is just random I guess):

```
[assembly: AssemblyVersion("4.1.0.*")]
```

And yes, there may be incompatabilities between 4.1.0.17 and 4.1.0.19 - I'm developing this one so, there are naturally changes :smile:

Actually I don't have a problem with this... But you seem to have a problem with this, and nuget... So, do I really need to update `AssemblyInfo.cs` and `ZeroMQ.nuspec` or what do you mean?

**Comment by goldenbull** [comment]
I'm OK with the version number reversal, it doesn't matter. I'm upgrading every project to 4.1.0.19, so there's nothing to do :smile:

**Comment by metadings** [comment]
Well doesn't do nuget this automatically?

**Comment by goldenbull** [comment]
no, because new version may break build. user have to upgrade explicitly using nuget command

**Comment by metadings** [comment]
Yes, they just have to :smile:

**Comment by metadings** [comment]
I want to have the nuget deployment as easy as possible... I'm going to change the version numbers explicitly. v4.1.0.20 will be the next, decreasing the number once again, but then the number is increasing by v4.1.0.21, .22, .23 and so on.

**Comment by goldenbull** [comment]
no problem, that sounds good :+1:
