### ISSUE TITLE
How to use libzmq 4.0.4

### ISSUE THREAD

**Issue by terelmj** [zeromq/clrzmq4#58]
Hi,
I installed this binding using NuGet, and it works correctly in my application. Since I wanted to use libzmq 4.0.4 I replaced the libzmq files in folders amd64 and i386, but it did not work, when I run the application I get the following error:

"The composition produced a single composition error. 
The root cause is provided below. 
Review the CompositionException.Errors property for more detailed information.\r\n\r\n1) 
The system cannot find the file specified\r\n\r\nResulting in: UnmanagedLibrary[libzmq] Unable to load library \"libzmq\" 
from \"D:\Users\210045196\AppData\Local\Temp\libzmq.dll\". .....

Am I missing something? 

Thanks,

Teresa

**Comment by metadings** [comment]
Hello Teresa,

Yes it is intended to do so, by just replacing files in folder `i386` and `amd64` and setting these files to `copy if newer`.

However, I didn't have a CompositionException before... This is possibly using the wrong MSVC version?

I also don't know if, using nuget, you just can place the files into these folders; they probably might be replaced using the files from the package.

So why do you use this very old version from the .msi package on zeromq.org ...? As said above, you might use a new version of MSVC and an old version of libzmq not compiled against the new MSVC... (Yes, I need to do something about the Platform loader...)

**Comment by terelmj** [comment]
Hi,

Yes, I was using the .msi package. I could not use the new MSVC but I had one libzmq 4.0.4 dll from another project (not sure how that one was generated) Once I replaced it, it worked perfectly. Thank You!

Teresa

**Comment by metadings** [comment]
You're welcome :smile:
