### ISSUE TITLE
System.AccessViolationException with Majordomo sample

### ISSUE THREAD

**Issue by cabrinoob** [zeromq/clrzmq4#59]
Hi,
I'am new to ZeroMQ and I'd like to evaluate the Majordomo pattern in C#. I have downloaded the samples and run the MDBroker, MDWorker (x4) and one MDClient2 (async mode).

In a run of 100000 calls, I randomly experience this error (on a worker side or the broker side) : 

`Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Buffer.Memmove(Byte* dest, Byte* src, UInt32 len)
at System.String.CtorCharPtrStartLength(Char* ptr, Int32 startIndex, Int32 length)
at ZeroMQ.ZFrame.ReadStringNative(Int32 byteCount, Encoding encoding)
at ZeroMQ.ZFrame.ReadString(Int32 length, Encoding encoding)
at ZeroMQ.ZFrame.ToString(Encoding encoding)
at ZeroMQ.ZFrame.ToString()
at Examples.Program.Main(String[] args) dans C:\SVN\Majordomo\Broker\Program.cs:ligne 554
`

I Compiled the Majordomo sample with Visual Studio 2015 under .NET 4.6 (Windows 8.1 Enterprise).

I have the the issue on an EC2 VM under Windows Server 2012 (I thought my problem was linked to my computer).

If I run the Broker in JAVA (with Jeromq lib) and keeping client and workers in c# (clrzmq4) I have no problem anymore.

Thank you for your help.

**Comment by metadings** [comment]
Well... I don't have a Windows computer currently, neiter a VM to run, so.... You need a copy of a new `libzmq.dll` and a new `libsodium.dll`, compiled against MSVC2015 `kernel32.dll` `LoadLibrary`, and put these files into the `amd64` folder!

I also sometimes "see" things, using Console.WriteLine the `(ZFrame)current.ToString()` ... 
There are sometimes funny "fragments"

**Comment by cabrinoob** [comment]
Hi, thank you for your advice, but this morning I build libzmq and libsodium on my computer from sources (for VS2015) and replace these 2 DLL in amd64 of my broker and worker but I still have this error.

These errors often occur in the MDP.cs file at line 40 : 

`public static bool StrHexEq(this ZFrame zfrm, MdpCommon.MdpwCmd cmd)
{
    return zfrm.ToString().ToMdCmd().Equals(cmd);
}
`

**Comment by metadings** [comment]
Aha... I didn't write the Majordomo examples, so I would have to try and debug too...

There maybe 
- a missing `using (frame)` or `frame.Dispose()`
- `if (frame.IsDismissed)`

**Comment by metadings** [comment]
I've made a Package update to nuget.org, and also updated the Release on github.

Now I'm also using a method [`EnumerateLibLdConf`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Posix.cs#L213) which enumerates `ld.so.conf`;
with the directive `include /etc/ld.so.conf.d/*.conf`, the method also looks into folders `/lib/`, `/usr/lib/`, `/usr/local/lib/` etc.
