### ISSUE TITLE
Bug with ZeroMQ.lib.zmq.Version Property in Visual Basic

### ISSUE THREAD

**Issue by matt109** [zeromq/clrzmq4#61]
Because visual basic is not case specific, am getting a: 'version' is ambiguous because multiple kinds of members with this name exist in class error... 

These 2 properties will need to be differentiated by more than just the cased v, to work with visual basic.

**Comment by metadings** [comment]
Can you use the other methods, or can't you use anything of this class?

**Comment by matt109** [comment]
It is just this method, you can't even see these methods with intellisense... it is because you have two methods with the same signature the only difference is the casing. Visual basic is NOT CASE SPECIFIC while C# is . The following would fix the issue:

Change: 
Public Shared ReadOnly version As zmq_version_delegate
Public Shared ReadOnly Version As Version

To 
Public Shared ReadOnly VersionDelegate As zmq_version_delegate
Public Shared ReadOnly Version As Version

**Comment by metadings** [comment]
Now I have renamed `Version` to `LibraryVersion`, to also have a `zmq.version` delegate:

```
-       public static readonly Version Version;
+       public static readonly Version LibraryVersion;
```

This now enables to have the original `zmq.version` function, and also a `zmq.LibraryVersion` property.

Look the [commit a1475027...](https://github.com/zeromq/clrzmq4/commit/a147502740ee747928ebe3ee6f2f417d55a0a5c3)!
