### ISSUE TITLE
Communicating with C++ ZMQ

### ISSUE THREAD

**Issue by acidos** [zeromq/clrzmq4#66]
I'm using 4.1.4 in my C++ app. This is a sample code:

```
char tempStr[] = "ABCD";
zmq_msg_t zmsg;
zmq_msg_init_size(&zmsg, 4);
memcpy(zmq_msg_data(&zmsg), tempStr, 4);
int rc = zmq_send(reqSocket, &zmsg, sizeof(zmsg), 0);
zmq_msg_close(&zmsg);
```

This will send 64 byte frame with actual ABCD from offset 16.

In C# I have:

```
ZFrame request = responder.ReceiveFrame();
byte[] reqBytes = new byte[100];
int n = request.Read(reqBytes, 0, 100);
```

reqBytes contains this 64 bytes and of course the actual data is located from offset 16. Question - how can I properly extract/construct data which is compatible with C++ zmq_msg_t at C# side? Hard coding offset looks very ugly.

**Comment by metadings** [comment]
> This will send 64 byte frame with actual ABCD from offset 16.

No. This will send 4 byte frame with actual ABCD from offset 0.

> How can I properly extract/construct data which is compatible with C++ zmq_msg_t at C# side? Hard coding offset looks very ugly.

Well... If you do so in C, having 16 bytes, then ABCD, then the rest,
you should also do this in C#, having 16 bytes, then ABCD, then the rest...

By the way, if you have a ZFrame, which is sent on REQ - REP sockets, you also need to answer using a ZFrame on REP - REQ sockets. Not sending an answer, ZeroMQ will repeat your question.
You may also use PUSH - PULL to send a ZFrame, which doesn't need the answer.

**Comment by acidos** [comment]
Turns out with new zmq_send/recv I don't need to wrap message into `zmq_msg_t`. It's done inside those functions. So now everything is perfect and C# side is receiving what I expect. Thanks for prompt response :)
