### ISSUE TITLE
NETCore Compatibility?

### ISSUE THREAD

**Issue by hismichael** [zeromq/clrzmq4#69]
ZeroMQ 4.1.0.21 is not compatible with netcoreapp1.0. Is there a plan for NETCore support?

**Comment by hismichael** [comment]
I'm on Ubuntu 16.04 and .NETCore 1.0.0 RC2

**Comment by metadings** [comment]
Well... I am currently on .NET Framework 4 / 4.5 and I am using `System.Threading.Thread` to implement static threading logic.

Now you say .NET Core 1, so you should make this program using `async` and `await` to implement threading logic.

So to say, there should be something like CoreZMQ or the like... :-)

**Comment by hismichael** [comment]
In fact, there is a pure C# zeromq called [NetMQ](https://github.com/zeromq/netmq/), while what I'm currently interested in is this C# binding.

It seems that one might be able to get it running on NETCore simply by a recompliation targeted to netcoreapp1.0. I've not yet tried that way.

**Comment by metadings** [comment]
Yes, this project is a binding in C# on C(++), look into `zmq.cs` and `Platform.cs`.
You may also use NetMQ, this is up to you.
And no, you can't just recompile this project in NETCore.
