### ISSUE TITLE
Why can't I use SetOption() to CURVE_SECRETKEY when using CurveZMQ?

### ISSUE THREAD

**Issue by fulinzhao** [zeromq/clrzmq4#70]
I want to use CurveZMQ to for secure authentication and confidentiality for communications between a client and a server. But I cannot find any example in C#. I try to follow the API document step by step. And I encounter the problem in Setting CURVE_PUBLICKEY, CURVE_SECRETKEY and CURVE_SERVERKEY.

Here is my code. 
The socket  'server.CurveSecretKey' threw an exception of type 'ZeroMQ.ZException': 
at ZeroMQ.ZSocket.GetOption(ZSocketOption option, IntPtr optionValue, Int32& optionLength)\r\n   at ZeroMQ.ZSocket.GetOption(ZSocketOption option, Byte[]& value)\r\n   at ZeroMQ.ZSocket.get_CurveSecretKey()"

```
public static byte[] StringToByteArray(string hex)
        {
            return Enumerable.Range(0, hex.Length)
                             .Where(x => x % 2 == 0)
                             .Select(x => Convert.ToByte(hex.Substring(x, 2), 16))
                             .ToArray();
        }

var context = new ZContext();
server = new ZSocket(context, ZSocketType.ROUTER);
server.SetOption(ZSocketOption.CURVE_SERVER, 1);
string curveSKey = "8E0BDD697628B91D8F245587EE95C5B04D48963F79259877B49CD9063AEAD3B7";
var skey = StringToByteArray(curveSKey);
server.SetOption(ZSocketOption.CURVE_SECRETKEY, skey);

```

**Comment by metadings** [comment]
Ya, well I had a problem with the compilation of libzmq on Windows... It seems that I've missed a compiler directive, which is enabling Curve25519... So to say, there is no Curve25519.

You need to recompile `i386\libzmq.dll`, `i386\libsodium.dll` and `amd64\libzmq.dll`, `amd64\libsodium.dll`. I don't have a Windows machine currently, I'm sorry.

**Comment by fulinzhao** [comment]
You mean, if I recompile i386\libzmq.dll, i386\libsodium.dll and amd64\libzmq.dll, amd64\libsodium.dll, will I achieve to use Curve? And I find there has few topics discussing about Curve in C#. I still have many questions about it. For example, I still don't know how to set certificate, is it needed to set certificate using Curve? Can you give me a simple Curve example in C#? Like "The Ironhouse Pattern, Model" 2 in http://hintjens.com/blog:49

**Comment by AlexanderShekhovcov** [comment]
@fulinzhao Have you found an example of using CurveZMQ in clrzmq4? 
I add encryption to my C# code like I did for nodejs and python, but the program works without encryption, 
REQ socket:
```
requester.CurvePublicKey = System.Text.Encoding.Unicode.GetBytes(<pub_key>);
requester.CurveSecretKey = System.Text.Encoding.Unicode.GetBytes(<secret_key>);
requester.CurveServerKey = System.Text.Encoding.Unicode.GetBytes(<server_key>);
...
```
REP socket
```
responder.CurvePublicKey = System.Text.Encoding.Unicode.GetBytes(<pub_key>);
responder.CurveSecretKey = System.Text.Encoding.Unicode.GetBytes(<secret_key>);
responder.CurveServer = true;
...
```
Looks like clrzmq4 just ignores those settings.

**Comment by metadings** [comment]
> You mean, if I recompile i386\libzmq.dll, i386\libsodium.dll and amd64\libzmq.dll, amd64\libsodium.dll, will I achieve to use Curve?

Yes. I've reverted libzmq.* and libsodium.* to the older version, just to have zmq_curve_keypair back.

> I still don't know how to set certificate, is it needed to set certificate using Curve?

No, the "certificate" is just a file containing the Curve keypair. You can do so by setting CURVE_PUBLICKEY, CURVE_SECRETKEY and CURVE_SERVERKEY.

> Can you give me a simple Curve example in C#?

Well currently not, but I want to implement Ironhouse and the like into [`metadings/zguide`](https://github.com/metadings/zguide)...
