### ISSUE TITLE
Problem with polling

### ISSUE THREAD

**Issue by peske** [zeromq/clrzmq4#73]
What I'm trying to accomplish is to implement reading a message from one of two sockets, wherever it arrives first. As far as I understand polling (`zmq_poll`) is the right thing to do (as demonstrated in [mspoller in guide](http://zguide.zeromq.org/cs:mspoller)). Here I'll provide small pseudo-code snippet:

```
TimeSpan timeout = TimeSpan.FromMilliseconds(50);

using (var receiver1 = new ZSocket(ZContext.Current, ZSocketType.DEALER))
using (var receiver2 = new ZSocket(ZContext.Current, ZSocketType.PAIR))
{
    receiver1.Bind("tcp://someaddress");
    // Note that PAIR socket is inproc:
    receiver2.Connect("inproc://otheraddress");

    var poll = ZPollItem.CreateReceiver();

    ZError error;
    ZMessage msg;

    while (true)
    {
        if (receiver1.PollIn(poll, out msg, out error, timeout))
        {
            // ...
        }

        if (receiver2.PollIn(poll, out msg, out error, timeout))
        {
            // ...
        }
    }
}
```

As you can see it is actually the same exact implementation as in [mspoller in guide](http://zguide.zeromq.org/cs:mspoller).

In my case `receiver2` (PAIR socket) should receive a large number of messages. In fact I've created a test in which number of messages sent to it is always greater than the number of messages it is capable to receive (at least in demonstrated implementation).

I've run the test for 2 seconds, and I was very surprised with results:
- Number of messages sent to `receiver2`: 180 (by "sent" I mean that they are handed out to another PAIR socket not shown in the previous snippet);
- Number of messages received by `receiver2`: 21 ??? Only 21 messages in 2 seconds??? 10 messages per second???

Then I've tried to play with different `timeout` values and I've found out that it significantly influences the number of messages received. Duration (2 seconds) and number of messages sent (180) remain the same. The results are:
- `timeout` value of 200 milliseconds - number of messages received drops to 10 (5 per second);
- `timeout` value of 10 milliseconds - number of messages received rises to 120 (60 per second).

The results are telling me that polling simply does not work. If polling were working properly, as far as I understand the mechanism, `timeout` should not have any influence in this scenario. No matter if we set timeout to 1 hour or 5 milliseconds - since there are always messages to receive there's nothing to wait for, so the loop should work with the same _speed_.

My another big concern is the fact that even with very small `timeout` value `receiver2` is not capable to receive all 180 messages. I'm struggling here to accomplish receiving rate of 100 messages per second, although I've selected ZeroMQ which should be very fast (benchmarks are mentioning numbers as 6 million messages per second).

So my question is obvious: am I doing something wrong here? Is there a better way to implement polling?

Thanks

**Comment by peske** [comment]
By browsing clrzmq4 code I've noticed that there's also possibility to call `pollIn` method on enumeration of sockets [ZPollItems.cs, line 151](https://github.com/zeromq/clrzmq4/blob/13ec05d5c899fee01ceef455f08309ee17b9a6f3/ZPollItems.cs#L151), but I haven't found any example anywhere!

Can this be the right approach? Any documentation anywhere?

Thanks

**Comment by peske** [comment]
I've found the problem / solution for this. Instead using `PollIn` method on each socket separately we should use `PollIn` method on array of sockets. Obviously [the example from the guide](http://zguide.zeromq.org/cs:mspoller) is **HUGELY MISLEADING**. Here's the correct approach:

```
TimeSpan timeout = TimeSpan.FromMilliseconds(50);

using (var receiver1 = new ZSocket(ZContext.Current, ZSocketType.DEALER))
using (var receiver2 = new ZSocket(ZContext.Current, ZSocketType.PAIR))
{
    receiver1.Bind("tcp://someaddress");
    receiver2.Connect("inproc://otheraddress");

    // We should "remember" the order of sockets within the array
    // because order of messages in the received array will correspond to it.
    ZSocket[] sockets = { receiver1, receiver2 };

    // Note that we should use two ZPollItem instances:
    ZPollItem[] pollItems = { ZPollItem.CreateReceiver(), ZPollItem.CreateReceiver() };

    ZError error;
    ZMessage[] msg;

    while (true)
    {
        if (sockets.PollIn(pollItems, out msg, out error, timeout))
        {
            if (msg[0] != null)
            {
                // The first message gotten from receiver1
            }

            if (msg[1] != null)
            {
                // The second message gotten from receiver2
            }
        }
    }
}
```

Now `receiver2` reaches 15,000 received messages per second, no matter `timeout` value, and no matter number of messages received by `receiver1`.

Although the issue is solved I'll left this open to increase visibility. If you don't agree with this - you can close it.

**Comment by metadings** [comment]
Could you please provide a "real" example, so I can run into this?

Note: It's not that `msg[0]` is the "first" message and `msg[1]` the "second" message. On a Dealer socket, forwarded by a Router socket, `msg[0]` is the Identity, `msg[1]` is empty and `msg[2]` contains your message. Otherwise, if it's just a Dealer socket you send messages to, `msg[0]` is your message and `msg[1]` doesn't exist at all.

Note2: Using an array for the sockets, you can't distinguish them from being received by `receiver1` or `receiver2`. You do always priorize polling in `receiver1`. You should separate both, so you really do poll both and not just one, every while.

**Comment by peske** [comment]
@metadings The example above is real. I'm not sure what else you want me to do with it?

> Note: It's not that msg[0] is the "first" message and msg[1] the "second" message. On a Dealer socket, forwarded by a Router socket, msg[0] is the Identity, msg[1] is empty and msg[2] contains your message. Otherwise, if it's just a Dealer socket you send messages to, msg[0] is your message and msg[1] doesn't exist at all.

You are completely wrong about this. You are talking about frames, but note that `msg` is array of messages (`ZMessage[]`), not array of frames. Each message within `msg` is (of course) enumeration of frames, so you can say that `msg[0][0]` is identity frame (assuming that `msg[0]` is not null).

> Note2: Using an array for the sockets, you can't distinguish them from being received by receiver1 or receiver2. You do always priorize polling in receiver1. You should separate both, so you really do poll both and not just one, every while.

Again wrong. Using an array of sockets allows you to get the message from any of the sockets included, wherever it arrives first. Or if there's a message ready at every socket - you'll get all the messages at once (that's the point of providing `ZMessage[]` as an output parameter). If you separate to two polls (as you're suggesting, and as the first example above does) - you'll stuck waiting for the message at socket which you are polling at the moment, no matter if other socket has hundreds of messages ready to be received.

I'm not sure if you've ever tried polling either way, but as you can see I've done testing with both approaches. With approach you are suggesting (the first approach on this page, and the _official_ approach in the guide) I've hardly reached 120 messages per second. But when I've switched to the second approach, I've reached 15,000 messages per second.

**Comment by peske** [comment]
Finally I have to say that the correct (the second) approach is already implemented in my system that deals with dozens of thousands forex prices (quotes) per second, and everything works like charm.

**Comment by peske** [comment]
@metadings Do you want me to provide you with the code that does the testing?

**Comment by metadings** [comment]
Well, I didn't see this, you are now using an array of ZMessages...
Actually, I don't get your problem here. What exact wording don't you like, or what do you like to get changed?

> The example above is real.

No, it isn't. There is no one who is connecting to your Dealer, there is a `tcp://someaddress`, and while the `inproc://otheraddress` may be used for real, there is no one binding a Pair socket. Finally, your example doesn't do anything with the received messages.

I also have to say, that I don't have influence on the ZGuide documentation itself; I just made the example, exactely doing in C# as one does using the C example.

**Comment by metadings** [comment]
> exactely doing in C# as one does using the C example.

Ha, I've got the problem. I'm not doing "exactely" what the C example does...

**Comment by peske** [comment]
If you are using polling on array of sockets - you have to use the array of `ZMessage` - there's no choice.

I'm not sure who is _in charge_ for the guide, but you should contact him to correct the example because (again) it is hugely misleading.

I will upload the complete project that does the testing if you want, and I'll send you the link but the point is actually very simple:

If you want to correctly do polling of two or more sockets in order to receive the message that is available at any of the sockets - **you have to use polling on array of sockets** as the second example on this page does. If you try polling one by one (as in the first example) - **it is not polling at all** - the software will wait for defined timeout period at the first socket no matter if there are thousands of messages ready on the second.

**Please try to update examples!!!** This misleading example has took me almost week in my tight schedule :)

Again, do you really need my complete testing code?

**Comment by metadings** [comment]
Well no, I may not need your test code... But I don't know now anymore which examples I do need with MSPoller and MSReader; TaskVent and WUServer?

**Comment by peske** [comment]
> No, it isn't. There is no one who is connecting to your Dealer, there is a `tcp://someaddress`, and while the `inproc://otheraddress` may be used for real, there is no one binding a Pair socket. Finally, your example doesn't do anything with the received messages.

Bit more info on how to reproduce:

No matter what endpoints you'll pick (i.e. `tcp://127.0.0.1:12345` and `inproc://myinproc`), and no matter what socket you'll connect from the outside to both DEALER and PAIR socket in the example (assuming of course that the sockets are compatible), you'll be able to detect the issue if one of polled sockets receives thousands of messages per second while the other receives only few (2-3). Due to the fact that polling the slower socket will block until it receives the message or its timeout expires - you'll receive only few messages per second in the fast socket also, although thousands will be ready for receiving.

**Comment by peske** [comment]
Well, the example that is especially painful is [mspoller](http://zguide.zeromq.org/cs:mspoller) since its very purpose is to demonstrate how to correctly use polling. You should correct this one first.

**Comment by metadings** [comment]
Now please have a look on [metadings/zguide](https://github.com/metadings/zguide/tree/master/examples/C%23) - I'm now waiting for my PR being committed; someone may also have to run a script to build the real zguide.zeromq.org, which is updating the example there.

**Comment by peske** [comment]
Talking about mspoller - that's it! Thanks!

About msreader - I must admit that I don't know what you've changed (nor what should be changed), so I suppose that it's OK too.

Sorry for bothering, and thanks in behalf of new ZeroMQ / clrzmq users who'll have the correct example to learn from!

**Comment by Haewk** [comment]
Thanks Peske. I ended up banging my head against the poller for a while and ended up writing my own poller. I may go and revisit that code now and try the example code you listed above.

**Comment by peske** [comment]
@Haewk - you're welcome :)

You can rest assured that above correct sample works like charm. I'm already using it in high-load production and it works great.
