### ISSUE TITLE
Misleading polling example ("Bug" in documentation) - attempt 2

### ISSUE THREAD

**Issue by peske** [zeromq/clrzmq4#75]
I have to try to reopen https://github.com/zeromq/clrzmq4/issues/74 since it is closed based on **WRONG** conclusions. (You can see more details at https://github.com/zeromq/clrzmq4/issues/73)

@metadings has closed the original issue although he hasn't actually understand the issue at all.

Again, I can confirm that I've tested everything multiple times, and that I'm already using the corrected approach in my production (dealing with dozens of thousands messages per second) without any problem. If you don't believe - simply do the testing your own. I've already provided the code.

**Comment by metadings** [comment]
Man, You don't need to re-open the issue a thousand times!
There is the one issue [#73](https://github.com/zeromq/clrzmq4/issues/73), and I just don't need to have your issue twice here.

**Comment by peske** [comment]
Sorry, but I've reopened it because you've closed it without actually understanding what I'm talking about, and based on **wrong** assumptions. I won't do this again.
