### ISSUE TITLE
Update to include libzmq 4.1.5

### ISSUE THREAD

**Issue by DCappsKSDL** [zeromq/clrzmq4#76]
The version of the native DLLs currently in clrzmq4 is a bit out of date - the main ZMQ project has release 4.1.5. It'd be good to update clrzmq4 to use this.

(For reference, the issue I'm having looks very much like https://github.com/zeromq/libzmq/issues/1542 which is fixed in 4.1.5, which is why I'm keen to see an update!)

As it happens, I've tried compiling libzmq myself, but I'm not having much luck. Additionally the Windows binary downloads on http://zeromq.org/distro:microsoft-windows aren't up to date, so there doesn't appear to be an easy way of me getting 4.1.5 binaries from there...

**Comment by metadings** [comment]
Yes, [zeromq.org/distro:microsoft-windows](http://zeromq.org/distro:microsoft-windows) is somewhat out of date.

No, I don't have a Windows machine to compile a new version. You need to make your own.

I've reverted to an older version of 4.1, just to have libsodium and zmq_curve_keypair.

**Comment by sigiesec** [comment]
libzmq is available via nuget: https://libraries.io/nuget/libzmq_vc120

This package could be referenced by clrzmq4. However, the DLLs contained in the package are named differently than currently assumed by clrzmq4 (the architecture etc. are encoded in the filename).

**Comment by sigiesec** [comment]
I updated the Windows libzmq.dll to version 4.2.2 by #117

**Comment by metadings** [comment]
I've updated Linux libzmq.so to version 4.1.7 by [commit/4d39464f405664af338292c88fef9bad55c80d3f](https://github.com/zeromq/clrzmq4/commit/4d39464f405664af338292c88fef9bad55c80d3f)

**Comment by metadings** [comment]
Closing this issue. It's too old

Look: I've removed amd64 and i386 folders from this git branch (or I hope so).
I'm including them just within [nuget.org/packages/ZeroMQ/4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30).
