### ISSUE TITLE
something wrong with PrefixStyle.None

### ISSUE THREAD

**Issue by fengzhi09** [zeromq/clrzmq4#77]
example code:

```
    var url = "tcp://*:5555";
    var style = PrefixStyle.None;

    //make response msg
    var responseMsg = new ResponseMessage()
    {
        code = ErrorCode.OK,
        type = MsgType.LOGIN,
        responseStr = "this is local server!"
    };
    var serverStream = new MemoryStream();
    ProtoBuf.Serializer.SerializeWithLengthPrefix(serverStream, responseMsg, style);

    // start server.
    var server = Task.Factory.StartNew(() => ZmqTools.WaitRequestFromClient(url, serverStream.GetBuffer()));

    //make request msg
    var clientMsg = new UserMessage() {login = new LoginMessage() {account = "xxx",password = "xxxxxx"}, type = MsgType.LOGIN};
    var clientStream = new MemoryStream();
    ProtoBuf.Serializer.Serialize(clientStream, clientMsg);

    var reply = ZmqTools.WaitReplyFormServer("tcp://127.0.0.1:5555", clientStream.GetBuffer());
    //Console.WriteLine($"client reply {reply}");

    var response = ProtoBuf.Serializer.DeserializeWithLengthPrefix<ResponseMessage>(reply,style);
    Console.WriteLine($"client response {response?.responseStr ?? "failed"}");

server.Wait(ZmqTools.TimeOut);
```

result:

> ```
>     client response failed
> ```

if i print the reply with code 

> ```
>     Console.WriteLine($"client reply {reply}");
> ```

results: 

> ```
>     client reply �this is local server!  
>     client response failed  
> ```
> 
> if i change the style like this:
> 
> ```
>     var style = PrefixStyle.Base128;
>     ......
>     //Console.WriteLine($"client reply {reply}");
> ```
> 
> results is ok.
> 
> ```
>     client response this is local server!
> ```
> 
> but if the server is writtern by c++ running on a linux
> everything goes the first case. i cannot  Deserialize the msg correctlly.
> something wrong to judge the head of a stream.

**Comment by metadings** [comment]
Well... I don't know about `PrefixStyle`, this is not part of `namespace ZeroMQ`.

Looks more like you'd like to do something like [`Espresso`](https://github.com/metadings/zguide/blob/master/examples/C%23/espresso.cs)...

However, because you want to use `Task` instead of `Thread`:You basically need to prepare all your Tasks, and then finally you await what the Task should have done.
