### ISSUE TITLE
How to use zeroMQ in desktop application

### ISSUE THREAD

**Issue by harikrishna553** [zeromq/clrzmq4#82]
I want to use ZeroMQ in my Desktop application. My Desktop application is deployed on Windows and Linux flavor operating systems.

I've gone through the url 'https://github.com/zeromq/clrzmq4' and I've seen the libraries separately built for amd64 and i386 processors.

My question is, 

a. do I need to build the libraries from source code for different processors? is it processor centric?
	
b. I want to use JeroMQ library in Java Environment, do I still require .dll files to use ZeroMQ in Java?
	
c. Do I require Visual Studio to build ZeroMQ libraries on Windows?

**Comment by metadings** [comment]
> do I need to build the libraries from source code for different processors? is it processor centric?

Yes.

> I want to use JeroMQ library in Java Environment

I don't know, this is C#.

> Do I require Visual Studio to build zeroMQ libraries in windows?

Yes.

**Comment by metadings** [comment]
> do I need to build the libraries from source code for different processors? is it processor centric?

Yes... ZeroMQ namespace is a framework which is basically built AnyCPU.. however this also a binding framework for [ZeroMQ/libzmq](https://github.com/ZeroMQ/libzmq) and [jedisct1/libsodium](https://github.com/jedisct1/libsodium). When compiling `libzmq`, you may also statically link [steve-o/openpgm](https://github.com/steve-o/openpgm) into your `libzmq.so` or `libzmq.dll`.

ZeroMQ is running on Win32 (VC2010), on Linux/Posix (GCC 4.8.x) and also Android and MacOSX.
This means you also have to install "vc2010redist.exe" (on Windows) or you do "apt-get install gcc" (on Linux).

**Comment by metadings** [comment]
reopening, because i love GitHub and it's open+closed "Visibility" ...

**Comment by metadings** [comment]
Closing this issue. It's too old
