### ISSUE TITLE
access violation exception (0xC0000005)

### ISSUE THREAD

**Issue by nileshbhope** [zeromq/clrzmq4#83]
I am using simple Publish socket to publish string data. As data is synschronous & no other thread accessing the broadcast method. Still I am getting frequent crash in my program, Below is crash dump report, Please let me know how to resolve this issue.

`
 Report for QX.MDManager__PID__2956__Date__01_17_2017__Time_02_12_37PM__209__Second_Chance_Exception_C0000005.dmp
Type of Analysis Performed   Crash Analysis 
Machine Name   WIN-BFRUTIQ2AQ6 
Operating System   Unexpected  
Number Of Processors   16 
Process ID   2956 
Process Image   C:\Program Files\QXT\Blitz Test1\QX.MDManager.exe 
System Up-Time   29 day(s) 21:28:56 
Process Up-Time   03:51:11 

Thread 14 - System ID 5076
Entry point   clr!DllUnregisterServerInternal+2a50c 
Create time   1/17/2017 10:21:35 AM 
Time spent in user mode   0 Days 0:0:9.578 
Time spent in kernel mode   0 Days 0:0:2.15 

Full Call Stack

Function     Arg 1     Arg 2     Arg 3     Arg 4   Source 
libzmq+17850     00000000`00000000     00000000`00000000     00000000`1d28fd30     00000000`1d28fb50    
libzmq+17895     00000000`1fd40f90     00000000`1d28fb50     00000000`1d28fb50     00000000`74ec20da    
libzmq+7d83     00000000`00000000     00000000`1fd40f90     00000000`1fd40e20     00000000`74ec5695    
libzmq+8085     00000000`1fd40f90     00000000`1d28fb50     00000000`1d28fb50     00000000`00000000    
libzmq+813b     00000000`00000058     00000000`00000000     00000000`00000000     00000000`206dd2d0    
libzmq!zmq_msg_set+1113f     00000000`00000000     00000000`00000058     00000000`1d28fb50     00000000`206dd4b8    
libzmq!zmq_msg_set+3eb     00000000`00000000     00000000`00000000     00000000`1fd40a40     00000000`03be5f40    
libzmq!zmq_has+66     00000000`1c211b70     00000000`206dd330     00000000`00000000     00000000`00000001    
0x00007ffd`2a175251     000091a7`af2662b8     00007ffd`899d9000     00000000`03be6050     00000000`00000001    
0x00007ffd`2a2816b6     00007ffd`2a2b8970     00000000`00000001     00000000`03be5f2c     00000000`2329ea88    
0x00007ffd`2a2812dd     00300030`00000032     00000000`00000000     00007ffd`8939a2f5     00000000`206dd148    
0x00007ffd`2a2811bc     00000000`206dec80     00000000`0377d930     00000000`00000000     00000000`031b6918    
0x00007ffd`2a28111e     00007ffd`2a13b448     00007ffd`2a1413c0     00000000`00000020     00000000`00000024    
0x00007ffd`2a281a48     00000000`031b6918     00000000`03be5e70     00000000`00000020     00000000`03be55d0    
0x00007ffd`2a19a4f7     00000000`031b6918     88d43ee2`e39d0000     00000000`00032cde     00000000`039803a8    
0x00007ffd`2a198cf5     00000000`206de7c0     00000000`206de7b8     00000000`206de7b0     00000000`00000000    
0x00007ffd`2a191701     00000000`032520a8     00000000`00000081     00000000`206de558     00000000`00000000    
0x00007ffd`2a0ba846     00000000`032520a8     00000000`00000000     00000000`00000000     00000000`00000000    
mscorlib_ni+478e45     00000000`00000000     00000000`00000000     00000000`00000000     00000000`00000000    
mscorlib_ni+478bb9     00000000`0377d998     00000000`00000000     00000000`00000000     00000000`00000000    
mscorlib_ni+478b97     00000000`0377d930     00000000`00000000     00000000`00000000     00000000`00000000    
mscorlib_ni+464291     00000000`0377d958     00000000`00000001     00000000`00000000     00000000`00000000    
clr!DllUnregisterServerInternal+1eb23     00000000`00000000     00000000`00000000     00000000`00000000     00000000`00000000    
clr!DllUnregisterServerInternal+1e9ee     00000000`00000001     00000000`00000004     00000000`206ded98     00000000`206dee58    
clr!DllUnregisterServerInternal+233b3     00000000`206df210     00000000`206df150     00007ffd`883fb0d8     00000000`1c211b70    
clr!DllUnregisterServerInternal+6d9     00000000`0377d958     00000000`206df150     00000000`1c211b70     00007ffd`8c235ec8    
clr!DllUnregisterServerInternal+3db19     00000000`206df150     00007ffd`89312b98     00000000`00000018     00007ffd`8931319a    
clr!DllUnregisterServerInternal+3daa0     00000000`00000001     00000000`00000001     00000000`00000000     00000000`00000000    
clr!DllUnregisterServerInternal+3da11     80000000`00000000     00000000`1c211b70     00000000`00000000     00000000`00000000    
clr!DllUnregisterServerInternal+3db53     00000000`1c211b70     00000000`00000001     00000000`00000000     00007ffd`00000006    
clr!DllUnregisterServerInternal+5ae     00000000`1c276c50     00000000`1c211b70     00000000`206df1e8     ffffffff`e3ded800    
clr!DllUnregisterServerInternal+2a582     00000000`00000000     00000000`00000000     00000000`00000000     00000000`00000000    
kernel32!BaseThreadInitThunk+d     00000000`00000000     00000000`00000000     00000000`00000000     00000000`00000000    
ntdll!RtlUserThreadStart+1d     00000000`00000000     00000000`00000000     00000000`00000000     00000000`00000000    

Exception Information
LIBZMQ+17850WARNING - DebugDiag was not able to locate debug symbols for libzmq.dll, so the information below may be incomplete.

In QX.MDManager__PID__2956__Date__01_17_2017__Time_02_12_37PM__209__Second_Chance_Exception_C0000005.dmp the assembly instruction at libzmq+17850 in C:\Program Files\QXT\Blitz Test1\amd64\libzmq.dll from iMatix Corporation has caused an access violation exception (0xC0000005) when trying to read from memory location 0x00000000 on thread 14

Module Information 
Image Name: C:\Program Files\QXT\Blitz Test1\amd64\libzmq.dll   Symbol Type:  Export 
Base address: 0x00000003`00905a4d   Time Stamp:  Fri Mar 18 19:24:36 2016  
Checksum: 0x00000000`00000000   Comments:   
COM DLL: False   Company Name:  iMatix Corporation 
ISAPIExtension: False   File Description:  ZeroMQ lightweight messaging kernel 
ISAPIFilter: False   File Version:  4.1.5.0 
Managed DLL: False   Internal Name:  zeromq 
VB DLL: False   Legal Copyright:  Copyright (c) 2012 The ZeroMQ Authors. 
Loaded Image Name:  libzmq.dll   Legal Trademarks:   
Mapped Image Name:     Original filename:  libzmq.dll 
Module name:  libzmq   Private Build:   
Single Threaded:  False   Product Name:  ZeroMQ 
Module Size:  580.00 KBytes   Product Version:  4.1.5.0 
Symbol File Name:  libzmq.dll   Special Build:  & 
 

`

**Comment by metadings** [comment]
I'm sorry, this dump says nothing...

Do you have some source code to look on?

**Comment by metadings** [comment]
I'm closing this issue, this is due to an old compilation of libzmq.dll and has nothing to do with this binding.
