### ISSUE TITLE
Disconnect the network and connect again

### ISSUE THREAD

**Issue by wenjians** [zeromq/clrzmq4#84]
Hi,
I tried the dealer (as client)/router(as server) mode, client send request to server for some operation, and server process it.

it works well in normal case. But when I plugged out the network and plugged in the network again, server can not receive message from client. Is anyone has the similar issue before?

but when I write similar code with C++ directory based on libzmq for both client and server, it works well after plug out/in the network. 

I install ZeroMQ and clrzmq with PM in visual studio 2013 directly, so the ZeroMQ library is 4.1.

**Comment by metadings** [comment]
Seems you solved this Issue as of [libzmq's Issue #2224](https://github.com/zeromq/libzmq/issues/2224)...
