### ISSUE TITLE
ZSocketType.STREAM behaving erratically

### ISSUE THREAD

**Issue by TkNeo** [zeromq/clrzmq4#87]
We have a client server application where the client will , say, send 300 requests to the server (socket type STREAM). The server will do some processing and respond back. So what happens is that all 300 requests show up at the server port immediately and the server is working through the list one by one. The server socket has to be of type STREAM in our case. We are noticing that if we send 10 requests the workflow works ok, but with a load of 100 the server starts to miss messages in some cases. The bytes received at the port are correct as we confirmed it with wireshark. But the parsing of the traffic at the STREAM port shows some frames got missed. 

Anyone using STREAM socket for heavy loads and knows it works ?

**Comment by sigiesec** [comment]
The clrzmq4 layer does not add any socket-type-specific behaviour, so this is probably a general ZeroMQ issue. It is best addressed to the zeromq-dev mailing list. Do you handle any possible EAGAIN errors? To be able to reproduce your issue, executable code would be very helpful.

**Comment by metadings** [comment]
Closing this issue. It's too old
