### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#92]
clrzmq4 does not contain any tests, which makes any changes very risky.

**Comment by sigiesec** [comment]
By #95, I added the basic infrastructure to write tests and to run appveyor CI. 

@metadings Could you add the project to appveyor?

**Comment by sigiesec** [comment]
@metadings I have not the appropriate github permissions to configure the project on appveyor. Can you do this? Or alternatively, if you assign the required permissions to my, I can configure that on appveyor (and coveralls, see #96).

**Comment by c-rack** [comment]
I've sent you an invitation as project admin. Please let me know if these rights are sufficient.

**Comment by sigiesec** [comment]
@c-rack Thanks a lot :) I can access the zeromq/clrzmq4 repo now at AppVeyor under my personal account. This leads to a URL that is linked to my account as well: https://ci.appveyor.com/project/sigiesec/clrzmq4-uhk9y
If I wanted to add a badge here, I would need to use that URL. That would work, but is probably not completely as intended. Is there a ZeroMQ organization account on AppVeyor? If I understand https://www.appveyor.com/docs/team-setup/ correctly, you need to add the clrzmq Administrators team there. Then, I should be able to configure it under the URL https://ci.appveyor.com/project/zeromq/clrzmq4 as well

**Comment by c-rack** [comment]
I have created a zeromq/clrzmq4 project on AppVeyor and extended permissions for "users". Could you please try again?

**Comment by sigiesec** [comment]
I see that https://ci.appveyor.com/project/zeromq/clrzmq4 now exists, but apparently I do not have permission to start a build or configure anything.

**Comment by c-rack** [comment]
Ok. Have you tried to logout and re-login in github and appveyor?
By the way, have you enabled 2FA on github?

**Comment by sigiesec** [comment]
I did re-login, but it did not change anything.
I have not enabled 2FA right now. Should I?

**Comment by c-rack** [comment]
If you enable 2FA, I could promote you to zeromq org admin, which should give you the rights you need.

**Comment by sigiesec** [comment]
Ok, I enabled 2FA now.

**Comment by c-rack** [comment]
Welcome on board. Please try again.

**Comment by sigiesec** [comment]
Thanks a lot :) But it did not help with this issue unfortunately :(
Now I see all zeromq projects when I try to add a new project on appveyor, but still only under my personal account. One possible issue might be that my GitHub user maps to multiple roles on Appveyor. If you don't have an idea how to solve it, I might open a support request at Appveyor.

**Comment by c-rack** [comment]
When you login to AppVeyor, you should see a select box if you want to login with your personal account or the organization account.

**Comment by sigiesec** [comment]
Hm, I don't. Did a re-login to GitHub and AppVeyor again... but I get logged in to my personal account within a selection box.

**Comment by c-rack** [comment]
Hm, weird. So first, I would downgrade the zeromq ownership, as this does not made the trick. You can become owner later if you are also contributing to other projects. ok?

Then, I have found the team permissions page on AppVeyor and added the clrzmq team. Also, I have added you as collaborator with admin settings to the zeromq AppVeyor team.

Could you please try it again?

**Comment by sigiesec** [comment]
Never mind :)

It works now! I am asked for the personal vs. organizational account now when logging in to AppVeyor now. And I could trigger a build. Thanks for the assistance!

Next, I will see what Coveralls.io says. But I think I don't need an organizational account there.

**Comment by sigiesec** [comment]
Looks good now, I also added badges to the front page via #103
