### ISSUE TITLE
signaler.cpp assertion failure reset by peer line 288 also occasionally line 171

### ISSUE THREAD

**Issue by UniversalAE** [zeromq/clrzmq4#99]
Using multiple Pub-Sub channels between multiple independent C# apps.   Windows 10 and Windows 7 OS.   The family of apps run from 2 to 6 hours error free with thousands of message transfers and then poof, all apps die simultaneously with the same assertion failure.  Each app is single threaded.  Each app has one ZMQ context. Each app has 7 sockets.  Some are sub and some are pub.  The failure is definitely coming out of ZMQ.  Does anyone know how to contain this so the application does not crash?   I need all of these apps monitoring various aspects of a 24/7 production process to run continuously error free forever.

CLR wrapper may not be at fault but clearly does not handle assertion failure.

**Comment by UniversalAE** [comment]
Exception occurs in ZeroMQ.lib.zmq.zmq_msg_recv.
Here is an update to the above problem showing the call stack and the actual exception number:
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at ZeroMQ.lib.zmq.zmq_msg_recv(IntPtr msg, IntPtr socket, Int32 flags)
   at ZeroMQ.ZSocket.ReceiveFrames[ListT](Int32& framesToReceive, ListT& frames, ZSocketFlags flags, ZError& error)
   at ZeroMQ.ZSocket.ReceiveFrames(Int32 framesToReceive, ZSocketFlags flags, ZError& error)
   at ZeroMQ.ZSocket.ReceiveFrame(ZSocketFlags flags, ZError& error)

**Comment by metadings** [comment]
Look, this is a binding to ZeroMQ, you should recompile `libzmq.dll` and `libzmq.so` and place these files in folders `amd64` and `x86`. The version supplied with this binding is somewhat outdated.

Then, if you did so, you may also issue this on zeromq/libzmq - I can't help you with asserts, which are immediately calling exit.

**Comment by UniversalAE** [comment]
Is libzmq.so necessary?  My C++ apps don't appear to be using it.  There is definitely a versioning mismatch.  The C++apps I have written are using the latest 4.2.3 static linked and C# with CLRZMQ4 is using 4.1.1 dynamic.   Uli, thanks for pointing this out.  The mismatch could be the source of the problem.  For anyone else that is interested, the 4.2.2 release notes suggest this exception triggered externally problem is resolved.  I won't know this for a fact until I get my ducks lined up.  I will post the results.

**Comment by UniversalAE** [comment]
This is an interim update on my progress.   I have removed all other apps from the communication channels and isolated the problem to only 2 apps running both C# with the same current release CLRZMQ4 bindings unmodified from the NuGet repositor.   Only one app uses one PUB channel to communicate to the other app.   The other app just receives SUB data from the PUB app.  The platform is Windows 10, the compiler is Visual Studio 2017.   At a little over 2 hours both apps crashed simultaneously with the same error message and the same symptoms reported in this thread.   Uli, I strongly urge you to update a patch release with the most recent ZMQ core.   This is because A, it may solve the problem and B, it brings CLRMQ4 equivalent to the rest of the world of ZMQ bindings.

**Comment by pblasucci** [comment]
Hi,

Would you be opposed to posting the minimum code needed to reproduce? I maintain an alternative CLR binding, and would like to see if my code base exhibits the same behavior.

Thanks.

Paul

_____________________________

**Comment by sigiesec** [comment]
See my suggestion under #76 on using the nuget package libzmq_vc120

**Comment by UniversalAE** [comment]
I'm closing my participation in this issue.   As metadings made reference, it appears to be a problem with ZeroMQ core.   It's a problem that others have reported for over a year and a half with no prospects for resolution.   I have moved on to RabbitMQ which works flawlessly.   **I urge everyone to stop wasting their time with ZeroMQ.**   It's damaged.   I now have 4 apps running simultaneously with 1 PUB and 3 SUB endpoints in each all intercommunicating at 5ms packet intervals.   The process has been running for days with no exception-assertion errors.  I have not encapsulated any of it in Try-Catch.   RabbitMQ simply works as expected.

**Comment by UniversalAE** [comment]
The move to RabbitMQ I reported 17 days ago has been so successful I feel compelled to report it.   ZERO truely ZERO errors since the last report.  It's been nearly a month of 24/7 messaging between all processes.  Millions of transactions.  Perhaps Billions of flawless object messaging transactions.

**Comment by metadings** [comment]
+++ :smile:

**Comment by metadings** [comment]
Didn't you update the Windows binary files (*.dll)?

I've updated Linux binaries (libzmq.so, curve_keygen), using [zeromq/zeromq4-1](https://github.com/zeromq/zeromq4-1) v4.1.7, with TweetNaCl, without epgm. [commit/4d39464f405664af338292c88fef9bad55c80d3f](//github.com/zeromq/clrzmq4/commit/4d39464f405664af338292c88fef9bad55c80d3f)

**Comment by metadings** [comment]
Can we close this issue?

**Comment by metadings** [comment]
Closing this issue. It's too old
